fluidShape = cmds.ls(sl=True, type="fluidShape")[0]
cmds.setAttr(fluidShape+".densityMethod", 2)
cmds.setAttr(fluidShape+".velocityMethod", 2)
cmds.setAttr(fluidShape+".transparency", 0.25, 0.25, 0.25, type="float3")
cmds.setAttr(fluidShape+".edgeDropoff", 0.0500000007451)
cmds.setAttr(fluidShape+".colorInput", 0)
cmds.setAttr(fluidShape+".colorInputBias", 0.0)
cmds.setAttr(fluidShape+".opacityInput", 5)
cmds.setAttr(fluidShape+".opacityInputBias", 0.0)
cmds.setAttr(fluidShape+".quality", 1.0)
cmds.setAttr(fluidShape+".contrastTolerance", 0.00999999977648)
cmds.setAttr(fluidShape+".renderInterpolator", 0)
cmds.setAttr(fluidShape+".colorTexture", False)
cmds.setAttr(fluidShape+".opacityTexture", False)
cmds.setAttr(fluidShape+".textureType", 0)
cmds.setAttr(fluidShape+".colorTexGain", 1.0)
cmds.setAttr(fluidShape+".opacityTexGain", 1.0)
cmds.setAttr(fluidShape+".amplitude", 1.0)
cmds.setAttr(fluidShape+".ratio ", 0.707000017166)
cmds.setAttr(fluidShape+".frequencyRatio", 2.0)
cmds.setAttr(fluidShape+".depthMax", 2)
cmds.setAttr(fluidShape+".invertTexture", False)
cmds.setAttr(fluidShape+".inflection", False)
cmds.setAttr(fluidShape+".textureTime", 0.0)
cmds.setAttr(fluidShape+".frequency", 1.0)
cmds.setAttr(fluidShape+".textureScaleX", 1.0)
cmds.setAttr(fluidShape+".textureScaleY", 1.0)
cmds.setAttr(fluidShape+".textureScaleZ", 1.0)
cmds.setAttr(fluidShape+".selfShadowing", False)
cmds.setAttr(fluidShape+".shadowOpacity", 0.5)
cmds.setAttr(fluidShape+".lightType", 1)
cmds.setAttr(fluidShape+".lightBrightness", 1.0)
cmds.setAttr(fluidShape+".fluidLightColor", 1.0, 1.0, 1.0, type="float3")
cmds.setAttr(fluidShape+".ambientBrightness", 0.0)
cmds.setAttr(fluidShape+".ambientDiffusion", 2.0)
cmds.setAttr(fluidShape+".ambientColor", 0.5, 0.699999988079, 1.0, type="float3")
cmds.setAttr(fluidShape+".directionalLightX", 0.5)
cmds.setAttr(fluidShape+".directionalLightY", 0.800000011921)
cmds.setAttr(fluidShape+".directionalLightZ", 0.5)
cmds.setAttr(fluidShape+".pointLightX", 0.0)
cmds.setAttr(fluidShape+".pointLightY", 0.0)
cmds.setAttr(fluidShape+".pointLightZ", 0.0)
cmds.setAttr(fluidShape+".pointLightDecay", 1)
cmds.setAttr(fluidShape+".opacity[0].opacity_Position", 0.0)
cmds.setAttr(fluidShape+".opacity[0].opacity_FloatValue", 0.0)
cmds.setAttr(fluidShape+".opacity[0].opacity_Interp", 1)
cmds.setAttr(fluidShape+".opacity[1].opacity_Position", 0.956521749496)
cmds.setAttr(fluidShape+".opacity[1].opacity_FloatValue", 0.319999992847)
cmds.setAttr(fluidShape+".opacity[1].opacity_Interp", 1)
cmds.setAttr(fluidShape+".opacity[2].opacity_Position", 0.0956521704793)
cmds.setAttr(fluidShape+".opacity[2].opacity_FloatValue", 0.600000023842)
cmds.setAttr(fluidShape+".opacity[2].opacity_Interp", 1)
cmds.setAttr(fluidShape+".opacity[3].opacity_Position", 0.40869563818)
cmds.setAttr(fluidShape+".opacity[3].opacity_FloatValue", 0.560000002384)
cmds.setAttr(fluidShape+".opacity[3].opacity_Interp", 1)
cmds.setAttr(fluidShape+".opacity[4].opacity_Position", 0.660869538784)
cmds.setAttr(fluidShape+".opacity[4].opacity_FloatValue", 0.379999995232)
cmds.setAttr(fluidShape+".opacity[4].opacity_Interp", 1)
cmds.setAttr(fluidShape+".opacity[5].opacity_Position", 0.930434763432)
cmds.setAttr(fluidShape+".opacity[5].opacity_FloatValue", 0.519999980927)
cmds.setAttr(fluidShape+".opacity[5].opacity_Interp", 1)
cmds.setAttr(fluidShape+".opacity[6].opacity_Position", 1.0)
cmds.setAttr(fluidShape+".opacity[6].opacity_FloatValue", 0.180000007153)
cmds.setAttr(fluidShape+".opacity[6].opacity_Interp", 1)
cmds.setAttr(fluidShape+".color[0].color_Position", 0.0)
cmds.setAttr(fluidShape+".color[0].color_Color", 1.0, 1.0, 1.0, type="float3")
cmds.setAttr(fluidShape+".color[0].color_Interp", 1)
cmds.setAttr(fluidShape+".color[1].color_Position", 0.469565212727)
cmds.setAttr(fluidShape+".color[1].color_Color", 1.0, 1.0, 1.0, type="float3")
cmds.setAttr(fluidShape+".color[1].color_Interp", 1)
cmds.setAttr(fluidShape+".color[2].color_Position", 0.904347836971)
cmds.setAttr(fluidShape+".color[2].color_Color", 0.0, 1.0, 1.0, type="float3")
cmds.setAttr(fluidShape+".color[2].color_Interp", 1)
cmds.setAttr(fluidShape+".incandescence[0].incandescence_Position", 0.0)
cmds.setAttr(fluidShape+".incandescence[0].incandescence_Color", 0.0, 0.0, 0.0, type="float3")
cmds.setAttr(fluidShape+".incandescence[0].incandescence_Interp", 1)
cmds.setAttr(fluidShape+".incandescence[1].incandescence_Position", 0.800000011921)
cmds.setAttr(fluidShape+".incandescence[1].incandescence_Color", 0.899999976158, 0.20000000298, 0.0, type="float3")
cmds.setAttr(fluidShape+".incandescence[1].incandescence_Interp", 1)
cmds.setAttr(fluidShape+".incandescence[2].incandescence_Position", 1.0)
cmds.setAttr(fluidShape+".incandescence[2].incandescence_Color", 1.5, 1.0, 0.0, type="float3")
cmds.setAttr(fluidShape+".incandescence[2].incandescence_Interp", 1)
cmds.setAttr(fluidShape+".incandescence[3].incandescence_Position", 0.330434769392)
cmds.setAttr(fluidShape+".incandescence[3].incandescence_Color", 0.391303986311, 0.0869565010071, 0.0, type="float3")
cmds.setAttr(fluidShape+".incandescence[3].incandescence_Interp", 1)
