set (support_icons_svg_files
    BUTTONS/adapt_h.svg
    BUTTONS/adapt_v.svg
    BUTTONS/add.svg
    BUTTONS/back.svg
    BUTTONS/bundle_add_selected.svg
    BUTTONS/bundle_remove_selected.svg
    BUTTONS/bundle_select.svg
    BUTTONS/bundle_select_add.svg
    BUTTONS/bundle_select_remove.svg
    BUTTONS/bundle_set_selected.svg
    BUTTONS/calc.svg
    BUTTONS/chooser.svg
    BUTTONS/chooser_color.svg
    BUTTONS/chooser_file.svg
    BUTTONS/chooser_folder.svg
    BUTTONS/chooser_geo.svg
    BUTTONS/chooser_image_color.svg
    BUTTONS/chooser_node.svg
    BUTTONS/clear.svg
    BUTTONS/close.svg
    BUTTONS/color.svg
    BUTTONS/color_temperature.svg
    BUTTONS/colors.svg
    BUTTONS/comment_out.svg
    BUTTONS/cook.svg
    BUTTONS/copy.svg
    BUTTONS/create_incontext.svg
    BUTTONS/create_objects.svg
    BUTTONS/create_parm_from_ch.svg
    BUTTONS/cut.svg
    BUTTONS/decrease_indent.svg
    BUTTONS/delete.svg
    BUTTONS/delete_folder.svg
    BUTTONS/delete_mini.svg
    BUTTONS/displayoptions.svg
    BUTTONS/down.svg
    BUTTONS/download.svg
    BUTTONS/duplicate.svg
    BUTTONS/dynamic_rgb_sliders.svg
    BUTTONS/dynamic_tmi_sliders.svg
    BUTTONS/edit.svg
    BUTTONS/editstate_edit.svg
    BUTTONS/editstate_sculpt.svg
    BUTTONS/editstate_slide.svg
    BUTTONS/equal.svg
    BUTTONS/external_editor.svg
    BUTTONS/fast.svg
    BUTTONS/favorites.svg
    BUTTONS/filter.svg
    BUTTONS/flatlist.svg
    BUTTONS/folder.svg
    BUTTONS/forward.svg
    BUTTONS/gamma.svg
    BUTTONS/gear.svg
    BUTTONS/gear_mini.svg
    BUTTONS/global.svg
    BUTTONS/grid.svg
    BUTTONS/help.svg
    BUTTONS/hide_controls.svg
    BUTTONS/history.svg
    BUTTONS/hscript.svg
    BUTTONS/icons_large.svg
    BUTTONS/icons_medium.svg
    BUTTONS/image_color_picker.svg
    BUTTONS/import_library.svg
    BUTTONS/increase_indent.svg
    BUTTONS/info.svg
    BUTTONS/jump.svg
    BUTTONS/jump_to_line.svg
    BUTTONS/layer_mute.svg
    BUTTONS/layer_mute_off.svg
    BUTTONS/layer_solo.svg
    BUTTONS/layer_solo_off.svg
    BUTTONS/light_mute.svg
    BUTTONS/light_solo.svg
    BUTTONS/link.svg
    BUTTONS/list_add.svg
    BUTTONS/list_delete.svg
    BUTTONS/list_reorderleft.svg
    BUTTONS/list_reorderup.svg
    BUTTONS/listview.svg
    BUTTONS/lock_closed.svg
    BUTTONS/lock_open.svg
    BUTTONS/match_pivot.svg
    BUTTONS/match_rotation.svg
    BUTTONS/match_scale.svg
    BUTTONS/match_transform.svg
    BUTTONS/materials_assigned.svg
    BUTTONS/materials_unassigned.svg
    BUTTONS/maximize.svg
    BUTTONS/minimize.svg
    BUTTONS/minimize_mini.svg
    BUTTONS/minus.svg
    BUTTONS/move_to_left.svg
    BUTTONS/move_to_right.svg
    BUTTONS/network_align_horizontal.svg
    BUTTONS/network_align_togrid.svg
    BUTTONS/network_align_vertical.svg
    BUTTONS/network_box.svg
    BUTTONS/network_distribute_horizontal.svg
    BUTTONS/network_distribute_vertical.svg
    BUTTONS/network_overview.svg
    BUTTONS/network_sticky.svg
    BUTTONS/network_treeview.svg
    BUTTONS/new_tab.svg
    BUTTONS/not_equal.svg
    BUTTONS/not_favorites.svg
    BUTTONS/pane_menu.svg
    BUTTONS/parmmenu_connected.svg
    BUTTONS/parmmenu_hidden.svg
    BUTTONS/parmmenu_parm.svg
    BUTTONS/parmmenu_texture.svg
    BUTTONS/paste.svg
    BUTTONS/pause.svg
    BUTTONS/pinned.svg
    BUTTONS/plus.svg
    BUTTONS/redo.svg
    BUTTONS/reload.svg
    BUTTONS/remove.svg
    BUTTONS/render.svg
    BUTTONS/reselect.svg
    BUTTONS/resimulate.svg
    BUTTONS/resimulate_inactive.svg
    BUTTONS/resizegrip_se.svg
    BUTTONS/restore.svg
    BUTTONS/restore_mini.svg
    BUTTONS/scope.svg
    BUTTONS/search.svg
    BUTTONS/search_and_replace.svg
    BUTTONS/secondary_colors.svg
    BUTTONS/show_controls.svg
    BUTTONS/stop.svg
    BUTTONS/subnet.svg
    BUTTONS/swatch_next.svg
    BUTTONS/swatch_previous.svg
    BUTTONS/switch.svg
    BUTTONS/sync.svg
    BUTTONS/tag.svg
    BUTTONS/take.svg
    BUTTONS/tearoff.svg
    BUTTONS/tree.svg
    BUTTONS/tree_minus.svg
    BUTTONS/tree_plus.svg
    BUTTONS/uncomment.svg
    BUTTONS/undo.svg
    BUTTONS/unpinned.svg
    BUTTONS/up.svg
    BUTTONS/update_ui.svg
    BUTTONS/uv_edge_cut.svg
    BUTTONS/uv_pin_add.svg
    BUTTONS/uv_pin_move.svg
    CHANNELS/bezier.svg
    CHANNELS/channelgroup.svg
    CHANNELS/constant.svg
    CHANNELS/cubic.svg
    CHANNELS/dope_region.svg
    CHANNELS/dope_ripple.svg
    CHANNELS/dope_select.svg
    CHANNELS/ease.svg
    CHANNELS/easein.svg
    CHANNELS/easeout.svg
    CHANNELS/handles_tie.svg
    CHANNELS/handles_untie.svg
    CHANNELS/linear.svg
    CHANNELS/match.svg
    CHANNELS/matchin.svg
    CHANNELS/matchout.svg
    CHANNELS/qlinear.svg
    CHANNELS/spline.svg
    CHANNELS/value_tie.svg
    CHANNELS/value_untie.svg
    CHANNELS/view_dopesheet.svg
    CHANNELS/view_graph.svg
    CHANNELS/view_table.svg
    CHOP/acoustic.svg
    CHOP/attribute.svg
    CHOP/audioin.svg
    CHOP/beat.svg
    CHOP/channel.svg
    CHOP/copy.svg
    CHOP/count.svg
    CHOP/cycle.svg
    CHOP/delay.svg
    CHOP/dynamics.svg
    CHOP/envelope.svg
    CHOP/fan.svg
    CHOP/foreach.svg
    CHOP/geometry.svg
    CHOP/handle.svg
    CHOP/iksolver.svg
    CHOP/image.svg
    CHOP/inversekin.svg
    CHOP/jiggle.svg
    CHOP/joystick.svg
    CHOP/keyboard.svg
    CHOP/lag.svg
    CHOP/logic.svg
    CHOP/merge.svg
    CHOP/object.svg
    CHOP/objectchain.svg
    CHOP/particle.svg
    CHOP/pitch.svg
    CHOP/pulse.svg
    CHOP/puppet.svg
    CHOP/resample.svg
    CHOP/spline.svg
    CHOP/spring.svg
    CHOP/transform.svg
    CHOP/transformchain.svg
    CHOP/voicesplit.svg
    CHOPVIEW/autoscroll.svg
    CHOPVIEW/currentframe.svg
    CHOPVIEW/star.svg
    CHOPVIEW/view_bar.svg
    CHOPVIEW/view_graph.svg
    COMMON/blend.svg
    COMMON/delete.svg
    COMMON/file.svg
    COMMON/merge.svg
    COMMON/null.svg
    COMMON/opengl.svg
    COMMON/openvdb.svg
    COMMON/ris.svg
    COMMON/subnet.svg
    COMMON/switch.svg
    COMMON/wrangle.svg
    COP2/add.svg
    COP2/anaglyph.svg
    COP2/atop.svg
    COP2/average.svg
    COP2/blend.svg
    COP2/blur.svg
    COP2/border.svg
    COP2/bright.svg
    COP2/bump.svg
    COP2/channelcopy.svg
    COP2/chromakey.svg
    COP2/color.svg
    COP2/colorcorrect.svg
    COP2/colorcurve.svg
    COP2/colormap.svg
    COP2/colorreplace.svg
    COP2/colorwheel.svg
    COP2/composite.svg
    COP2/contrast.svg
    COP2/convert.svg
    COP2/convolve.svg
    COP2/cornerramp.svg
    COP2/crop.svg
    COP2/defocus.svg
    COP2/deform.svg
    COP2/degrain.svg
    COP2/deinterlace.svg
    COP2/denoise.svg
    COP2/depthdarken.svg
    COP2/diff.svg
    COP2/dilateerode.svg
    COP2/dof.svg
    COP2/dropshadow.svg
    COP2/dsmflatten.svg
    COP2/edge.svg
    COP2/edgeblur.svg
    COP2/emboss.svg
    COP2/env.svg
    COP2/equalize.svg
    COP2/expand.svg
    COP2/extend.svg
    COP2/fetch.svg
    COP2/fieldmerge.svg
    COP2/fieldsplit.svg
    COP2/fieldswap.svg
    COP2/file.svg
    COP2/flip.svg
    COP2/fog.svg
    COP2/font.svg
    COP2/frontface.svg
    COP2/function.svg
    COP2/gamma.svg
    COP2/geokey.svg
    COP2/geometry.svg
    COP2/gradient.svg
    COP2/grain.svg
    COP2/hsv.svg
    COP2/huecurve.svg
    COP2/illpixel.svg
    COP2/inside.svg
    COP2/interlace.svg
    COP2/invert.svg
    COP2/layer.svg
    COP2/levels.svg
    COP2/light.svg
    COP2/limit.svg
    COP2/lookup.svg
    COP2/lumakey.svg
    COP2/lumamatte.svg
    COP2/mask.svg
    COP2/max.svg
    COP2/median.svg
    COP2/merge.svg
    COP2/min.svg
    COP2/mono.svg
    COP2/mosaic.svg
    COP2/multiply.svg
    COP2/noise.svg
    COP2/outside.svg
    COP2/over.svg
    COP2/pin.svg
    COP2/pixel.svg
    COP2/premultiply.svg
    COP2/pulldown.svg
    COP2/pushup.svg
    COP2/quantize.svg
    COP2/radialblur.svg
    COP2/ramp.svg
    COP2/reference.svg
    COP2/rename.svg
    COP2/reverse.svg
    COP2/rotoshape.svg
    COP2/scale.svg
    COP2/screen.svg
    COP2/sequence.svg
    COP2/shape.svg
    COP2/sharpen.svg
    COP2/shift.svg
    COP2/shuffle.svg
    COP2/skyenvmap.svg
    COP2/snip.svg
    COP2/still.svg
    COP2/streak.svg
    COP2/subtract.svg
    COP2/swap.svg
    COP2/switchalpha.svg
    COP2/tile.svg
    COP2/tima.svg
    COP2/timefilter.svg
    COP2/timescale.svg
    COP2/trim.svg
    COP2/under.svg
    COP2/unpin.svg
    COP2/uvmap.svg
    COP2/vector.svg
    COP2/velblur.svg
    COP2/vexfilter.svg
    COP2/vexgenerate.svg
    COP2/warp.svg
    COP2/window.svg
    COP2/wipe.svg
    COP2/xform.svg
    COP2/xor.svg
    COP2/zcomp.svg
    CROWDS/agent.svg
    CROWDS/agent2.svg
    CROWDS/agentcam.svg
    CROWDS/agentedit.svg
    CROWDS/agentlayer.svg
    CROWDS/agentlookat.svg
    CROWDS/agentterrainadaptation.svg
    CROWDS/agentterrainprojection.svg
    CROWDS/crowdobject.svg
    CROWDS/crowdsolver.svg
    CROWDS/crowdsource.svg
    CROWDS/obstacle.svg
    CROWDS/popsteeralign.svg
    CROWDS/popsteeravoid.svg
    CROWDS/popsteercohesion.svg
    CROWDS/popsteercustom.svg
    CROWDS/popsteerobstacle.svg
    CROWDS/popsteerpath.svg
    CROWDS/popsteerseek.svg
    CROWDS/popsteerseparate.svg
    CROWDS/popsteerturnconstraint.svg
    CROWDS/popsteerwander.svg
    CROWDS/populate.svg
    CROWDS/simulate.svg
    CROWDS/state.svg
    CROWDS/transition.svg
    CROWDS/trigger.svg
    CROWDS/triggerlogic.svg
    DATATYPES/angle.svg
    DATATYPES/boolean.svg
    DATATYPES/bundle.svg
    DATATYPES/bundle_smart.svg
    DATATYPES/button.svg
    DATATYPES/cvex.svg
    DATATYPES/cvex_folder.svg
    DATATYPES/data.svg
    DATATYPES/direction_vector.svg
    DATATYPES/file.svg
    DATATYPES/flag.svg
    DATATYPES/float.svg
    DATATYPES/float_log.svg
    DATATYPES/folder.svg
    DATATYPES/geo_file.svg
    DATATYPES/code_class.svg
    DATATYPES/code_function.svg
    DATATYPES/code_keyword.svg
    DATATYPES/code_method.svg
    DATATYPES/code_module.svg
    DATATYPES/code_type.svg
    DATATYPES/code_variable.svg
    DATATYPES/image_file.svg
    DATATYPES/int.svg
    DATATYPES/int_log.svg
    DATATYPES/int_vector.svg
    DATATYPES/int_vector2.svg
    DATATYPES/int_vector4.svg
    DATATYPES/label.svg
    DATATYPES/material_override.svg
    DATATYPES/matrix.svg
    DATATYPES/matrix3.svg
    DATATYPES/node_list.svg
    DATATYPES/node_path.svg
    DATATYPES/ordinal_menu.svg
    DATATYPES/override_folder.svg
    DATATYPES/override_set.svg
    DATATYPES/parameter.svg
    DATATYPES/parameter_channel.svg
    DATATYPES/parameter_override.svg
    DATATYPES/ramp.svg
    DATATYPES/rgb.svg
    DATATYPES/rgba.svg
    DATATYPES/rgba_mask.svg
    DATATYPES/separator.svg
    DATATYPES/string.svg
    DATATYPES/style.svg
    DATATYPES/styles_folder.svg
    DATATYPES/stylesheet.svg
    DATATYPES/stylesheet_condition.svg
    DATATYPES/stylesheet_spec.svg
    DATATYPES/uv.svg
    DATATYPES/uvw.svg
    DATATYPES/vector.svg
    DATATYPES/vector2.svg
    DATATYPES/vector4.svg
    DATATYPES/vex.svg
    DESKTOP/application.svg
    DESKTOP/application2.svg
    DESKTOP/application_mac.svg
    DESKTOP/blank.svg
    DESKTOP/blank2.svg
    DESKTOP/cdrom.svg
    DESKTOP/chan.svg
    DESKTOP/drive.svg
    DESKTOP/escape.svg
    DESKTOP/geo.svg
    DESKTOP/hip.svg
    DESKTOP/hipnc.svg
    DESKTOP/ifd.svg
    DESKTOP/installer.svg
    DESKTOP/installer2.svg
    DESKTOP/otl.svg
    DESKTOP/pic.svg
    DESKTOP/rat.svg
    DESKTOP/removable.svg
    DESKTOP/shortcut.svg
    DESKTOP/virtual.svg
    DIALOG/error.svg
    DIALOG/important.svg
    DIALOG/info.svg
    DIALOG/question.svg
    DIALOG/warning.svg
    DOP/affector.svg
    DOP/anchor.svg
    DOP/applydata.svg
    DOP/applyrel.svg
    DOP/bulletdata.svg
    DOP/bulletsolver.svg
    DOP/clothattachtobody.svg
    DOP/clothbodycollider.svg
    DOP/clothforces.svg
    DOP/clothobject.svg
    DOP/clothsolver.svg
    DOP/clothstitchconstraint.svg
    DOP/constraint.svg
    DOP/constraintnetwork.svg
    DOP/copydata.svg
    DOP/crowdfuzzylogic.svg
    DOP/dop.svg
    DOP/drag.svg
    DOP/embedhighresobject.svg
    DOP/emptyobject.svg
    DOP/fan.svg
    DOP/fetchdata.svg
    DOP/filamentsolver.svg
    DOP/filedata.svg
    DOP/finiteelementsolver.svg
    DOP/flipobject.svg
    DOP/flipsolver.svg
    DOP/fluidforce.svg
    DOP/fluidobject.svg
    DOP/fluidsolver.svg
    DOP/fracturedsolidobject.svg
    DOP/gas.svg
    DOP/gascurveforce.svg
    DOP/gasparticlecount.svg
    DOP/gasupres.svg
    DOP/gravity.svg
    DOP/groundplane.svg
    DOP/group.svg
    DOP/impulseforce.svg
    DOP/intangiblevalue.svg
    DOP/magnetforce.svg
    DOP/makeactive.svg
    DOP/makepassive.svg
    DOP/mask.svg
    DOP/matrixfield.svg
    DOP/matrixfieldvisualization.svg
    DOP/motion.svg
    DOP/multisolver.svg
    DOP/noise.svg
    DOP/objpos.svg
    DOP/oceansource.svg
    DOP/parentfluid.svg
    DOP/particlefieldvisualization.svg
    DOP/particlefluidemitter.svg
    DOP/particlefluidobject.svg
    DOP/particlefluidsink.svg
    DOP/particlefluidsolver.svg
    DOP/pointpos.svg
    DOP/popadvectbyfilaments.svg
    DOP/popcurveforce.svg
    DOP/popobject.svg
    DOP/popsolver.svg
    DOP/popvop.svg
    DOP/popwrangle.svg
    DOP/position.svg
    DOP/pyrosolver.svg
    DOP/rbdangularconstraint.svg
    DOP/rbdangularspringconstraint.svg
    DOP/rbdautofreeze.svg
    DOP/rbdconetwistconstraint.svg
    DOP/rbdfracturedobject.svg
    DOP/rbdglueobject.svg
    DOP/rbdhingeconstraint.svg
    DOP/rbdkeyactive.svg
    DOP/rbdobject.svg
    DOP/rbdpackedobject.svg
    DOP/rbdpinconstraint.svg
    DOP/rbdpointobject.svg
    DOP/rbdragdollobject.svg
    DOP/rbdsliderconstraint.svg
    DOP/rbdsolver.svg
    DOP/rbdspringconstraint.svg
    DOP/removeobject.svg
    DOP/resizefluid.svg
    DOP/rippleobject.svg
    DOP/ripplesolver.svg
    DOP/sandobject.svg
    DOP/sandsolver.svg
    DOP/sbdpinconstraint.svg
    DOP/sbdspringconstraint.svg
    DOP/scalarfield.svg
    DOP/scalarfieldvisualization.svg
    DOP/slicealongline.svg
    DOP/sliceplane.svg
    DOP/smokeobject.svg
    DOP/smokesolver.svg
    DOP/solidobject.svg
    DOP/sourcefilaments.svg
    DOP/split.svg
    DOP/squishyobject.svg
    DOP/staticobject.svg
    DOP/staticsolver.svg
    DOP/surfacecollisionparms.svg
    DOP/switchsolver.svg
    DOP/terrainobject.svg
    DOP/uniformforce.svg
    DOP/vectorfield.svg
    DOP/vectorfieldvisualization.svg
    DOP/vexforce.svg
    DOP/vopforce.svg
    DOP/vortexforce.svg
    DOP/whitewateremitter.svg
    DOP/whitewatersolver.svg
    DOP/windforce.svg
    DOP/wireangularconstraint.svg
    DOP/wireangularspringconstraint.svg
    DOP/wireglueconstraint.svg
    DOP/wireobject.svg
    DOP/wiresolver.svg
    FUR/add_dynamics.svg
    FUR/add_fur.svg
    FUR/addparting.svg
    FUR/adjust_length.svg
    FUR/brush.svg
    FUR/brush2.svg
    FUR/clump_hair.svg
    FUR/color.svg
    FUR/comb.svg
    FUR/cut_hair.svg
    FUR/density.svg
    FUR/hair2.svg
    FUR/length.svg
    FUR/lift_hair.svg
    FUR/orientation.svg
    FUR/paint_base_color.svg
    FUR/paint_bend_noise.svg
    FUR/paint_clumping.svg
    FUR/paint_comb_noise.svg
    FUR/paint_density.svg
    FUR/paint_frizz.svg
    FUR/paint_frizz_frequency.svg
    FUR/paint_frizz_roughness.svg
    FUR/paint_guard_density.svg
    FUR/paint_guard_length.svg
    FUR/paint_length.svg
    FUR/paint_twist.svg
    FUR/paint_twist_noise.svg
    FUR/paint_white_density.svg
    FUR/part_hair.svg
    FUR/plant_guides.svg
    FUR/reguide.svg
    FUR/screen_brush.svg
    FUR/shears.svg
    FUR/smooth.svg
    FUR/surface_brush.svg
    FUR/swirl.svg
    FUR/thickness.svg
    IMAGE/actual_size.svg
    IMAGE/adaptpixelrange.svg
    IMAGE/blackpoint.svg
    IMAGE/bright_shift.svg
    IMAGE/brightness.svg
    IMAGE/components_all.svg
    IMAGE/components_alpha.svg
    IMAGE/components_blue.svg
    IMAGE/components_green.svg
    IMAGE/components_red.svg
    IMAGE/contrast.svg
    IMAGE/diff_blend.svg
    IMAGE/diff_compare.svg
    IMAGE/diff_frame_current.svg
    IMAGE/diff_frame_next.svg
    IMAGE/diff_frame_offset.svg
    IMAGE/diff_frame_previous.svg
    IMAGE/diff_frame_specific.svg
    IMAGE/diff_highlight.svg
    IMAGE/diff_off.svg
    IMAGE/diff_split_h.svg
    IMAGE/diff_split_v.svg
    IMAGE/disconnect.svg
    IMAGE/fit_to_window.svg
    IMAGE/follow_display.svg
    IMAGE/follow_displayandselection.svg
    IMAGE/follow_selection.svg
    IMAGE/gamma.svg
    IMAGE/home.svg
    IMAGE/lut_off.svg
    IMAGE/lut_on.svg
    IMAGE/new_sequence.svg
    IMAGE/view_alpha.svg
    IMAGE/view_aspectratio.svg
    IMAGE/view_bgimage.svg
    IMAGE/view_guides.svg
    IMAGE/view_handles.svg
    IMAGE/view_histogram.svg
    IMAGE/view_image.svg
    IMAGE/view_labels.svg
    IMAGE/view_preview.svg
    IMAGE/view_rulers.svg
    IMAGE/view_timeline.svg
    IMAGE/viewport_linkscrolling.svg
    IMAGE/viewport_maximize.svg
    IMAGE/whitepoint.svg
    IMAGE/window_doublesize.svg
    IMAGE/window_halfsize.svg
    IMAGE/zoom_in.svg
    IMAGE/zoom_out.svg
    KEYS/Down.svg
    KEYS/Left.svg
    KEYS/LMB.svg
    KEYS/MMB.svg
    KEYS/mouse.svg
    KEYS/mouse_wheel.svg
    KEYS/Right.svg
    KEYS/RMB.svg
    KEYS/Up.svg
    MISC/angry_fruit_salad.svg
    MISC/checkmark.svg
    MISC/digital_asset.svg
    MISC/done_uploading.svg
    MISC/faq.svg
    MISC/field.svg
    MISC/generic.svg
    MISC/hor_arrow.svg
    MISC/installed.svg
    MISC/loading.svg
    MISC/logo.svg
    MISC/new.svg
    MISC/opensubdiv.svg
    MISC/orbolt.svg
    MISC/present.svg
    MISC/python.svg
    MISC/python_official.svg
    MISC/random.svg
    MISC/rating_empty.svg
    MISC/rating_full.svg
    MISC/rating_half.svg
    MISC/rename.svg
    MISC/satchel.svg
    MISC/selene.svg
    MISC/shelf.svg
    MISC/starthere.svg
    MISC/test.svg
    MISC/tier_one.svg
    MISC/tier_two.svg
    MISC/tooltip_type_indicator.svg
    MISC/tutorials.svg
    MISC/type_indicator.svg
    MISC/ui.svg
    MISC/update_available.svg
    MISC/update_circle.svg
    MISC/uploading.svg
    MISC/visualize.svg
    NETWORKS/chop.svg
    NETWORKS/cop2.svg
    NETWORKS/dop.svg
    NETWORKS/generic.svg
    NETWORKS/obj.svg
    NETWORKS/pop.svg
    NETWORKS/root.svg
    NETWORKS/rop.svg
    NETWORKS/scene.svg
    NETWORKS/shop.svg
    NETWORKS/vop.svg
    NETWORKS/vop_pop.svg
    NETWORKS/vop_sop.svg
    NODEFLAGS/audio.svg
    NODEFLAGS/bone.svg
    NODEFLAGS/bypass.svg
    NODEFLAGS/capture.svg
    NODEFLAGS/diskcache.svg
    NODEFLAGS/display.svg
    NODEFLAGS/export.svg
    NODEFLAGS/expose.svg
    NODEFLAGS/graph.svg
    NODEFLAGS/hardlock.svg
    NODEFLAGS/hidden.svg
    NODEFLAGS/highlight.svg
    NODEFLAGS/lock.svg
    NODEFLAGS/origin.svg
    NODEFLAGS/output.svg
    NODEFLAGS/render.svg
    NODEFLAGS/select.svg
    NODEFLAGS/selectabletemplate.svg
    NODEFLAGS/softlock.svg
    NODEFLAGS/template.svg
    NODEFLAGS/unload.svg
    NODEFLAGS/vop_names_long.svg
    NODEFLAGS/vop_names_short.svg
    NODEFLAGS/vop_terminals_all.svg
    NODEFLAGS/vop_terminals_collapsed.svg
    NODEFLAGS/vop_terminals_connected.svg
    NODEFLAGS/xray.svg
    OBJ/ambient.svg
    OBJ/autorig.svg
    OBJ/autorig_arm.svg
    OBJ/autorig_hand.svg
    OBJ/autorig_head.svg
    OBJ/autorig_leg.svg
    OBJ/autorig_quadruped.svg
    OBJ/autorig_quadruped_backleg.svg
    OBJ/autorig_quadruped_frontleg.svg
    OBJ/autorig_quadruped_head.svg
    OBJ/autorig_quadruped_spine.svg
    OBJ/autorig_quadruped_tail.svg
    OBJ/autorig_quadruped_toes.svg
    OBJ/autorig_spine.svg
    OBJ/autorig_spine_3.svg
    OBJ/autorig_spine_5.svg
    OBJ/blend.svg
    OBJ/blendsticky.svg
    OBJ/bone.svg
    OBJ/camera.svg
    OBJ/character_placer.svg
    OBJ/dopnet.svg
    OBJ/extractgeo.svg
    OBJ/fetch.svg
    OBJ/fog.svg
    OBJ/geo.svg
    OBJ/handle.svg
    OBJ/hlight.svg
    OBJ/instance.svg
    OBJ/lensflare.svg
    OBJ/light.svg
    OBJ/light_area.svg
    OBJ/light_caustic.svg
    OBJ/light_directional.svg
    OBJ/light_environment.svg
    OBJ/light_fluorescent.svg
    OBJ/light_geo.svg
    OBJ/light_gi.svg
    OBJ/light_point.svg
    OBJ/light_portal.svg
    OBJ/light_sky.svg
    OBJ/light_spot.svg
    OBJ/microphone.svg
    OBJ/muscle.svg
    OBJ/null.svg
    OBJ/path.svg
    OBJ/pathcv.svg
    OBJ/rivet.svg
    OBJ/simplebiped.svg
    OBJ/simplefemale.svg
    OBJ/sound.svg
    OBJ/stereocamera.svg
    OBJ/sticky.svg
    OBJ/switcher.svg
    OBJ/tooncharacter.svg
    OBJ_STATE/aligncapturepose.svg
    OBJ_STATE/blendpose.svg
    OBJ_STATE/bones.svg
    OBJ_STATE/bonesfromcurve.svg
    OBJ_STATE/dynamicparent.svg
    OBJ_STATE/editcaptureblend.svg
    OBJ_STATE/editcaptureregion.svg
    OBJ_STATE/editcaptureweight.svg
    OBJ_STATE/mirrorcapture.svg
    OBJ_STATE/paintcapturelayer.svg
    OBJ_STATE/path.svg
    OBJ_STATE/pose.svg
    old/chop/acoustic.svg
    old/chop/app.svg
    old/chop/area.svg
    old/chop/attribute.svg
    old/chop/audioin.svg
    old/chop/audioperiod.svg
    old/chop/band.svg
    old/chop/beat.svg
    old/chop/blend.svg
    old/chop/comp.svg
    old/chop/constant.svg
    old/chop/copy.svg
    old/chop/count.svg
    old/chop/cycle.svg
    old/chop/delay.svg
    old/chop/delete.svg
    old/chop/dynamics.svg
    old/chop/envelope.svg
    old/chop/export.svg
    old/chop/express.svg
    old/chop/extend.svg
    old/chop/fan.svg
    old/chop/feedback.svg
    old/chop/fetch.svg
    old/chop/fglove.svg
    old/chop/file.svg
    old/chop/filter.svg
    old/chop/fit.svg
    old/chop/fourier.svg
    old/chop/function.svg
    old/chop/geometry.svg
    old/chop/gesture.svg
    old/chop/handle.svg
    old/chop/hold.svg
    old/chop/image.svg
    old/chop/interp.svg
    old/chop/inversekin.svg
    old/chop/join.svg
    old/chop/keyboard.svg
    old/chop/lag.svg
    old/chop/limit.svg
    old/chop/logic.svg
    old/chop/lookup.svg
    old/chop/match.svg
    old/chop/math.svg
    old/chop/merge.svg
    old/chop/midiin.svg
    old/chop/midiout.svg
    old/chop/minibird.svg
    old/chop/mixer.svg
    old/chop/mouse.svg
    old/chop/network.svg
    old/chop/noise.svg
    old/chop/null.svg
    old/chop/object.svg
    old/chop/opgroup.svg
    old/chop/oscillator.svg
    old/chop/para.svg
    old/chop/particle.svg
    old/chop/pass.svg
    old/chop/phoneme.svg
    old/chop/pipein.svg
    old/chop/pipeout.svg
    old/chop/pitch.svg
    old/chop/pretransform.svg
    old/chop/pulse.svg
    old/chop/puppet.svg
    old/chop/record.svg
    old/chop/rename.svg
    old/chop/reorder.svg
    old/chop/resample.svg
    old/chop/sample.svg
    old/chop/sequence.svg
    old/chop/shift.svg
    old/chop/shuffle.svg
    old/chop/slope.svg
    old/chop/spatial.svg
    old/chop/spectrum.svg
    old/chop/spline.svg
    old/chop/spring.svg
    old/chop/stretch.svg
    old/chop/subnet.svg
    old/chop/switch.svg
    old/chop/transform.svg
    old/chop/trigger.svg
    old/chop/trim.svg
    old/chop/vex.svg
    old/chop/voicesplit.svg
    old/chop/voicesync.svg
    old/chop/warp.svg
    old/chop/wave.svg
    old/cop2/add.svg
    old/cop2/atop.svg
    old/cop2/average.svg
    old/cop2/blend.svg
    old/cop2/blur.svg
    old/cop2/border.svg
    old/cop2/bright.svg
    old/cop2/bump.svg
    old/cop2/channelcopy.svg
    old/cop2/chromakey.svg
    old/cop2/circle.svg
    old/cop2/color.svg
    old/cop2/colorcorrect.svg
    old/cop2/colorcurve.svg
    old/cop2/colormap.svg
    old/cop2/colorreplace.svg
    old/cop2/colorwheel.svg
    old/cop2/composite.svg
    old/cop2/contrast.svg
    old/cop2/convert.svg
    old/cop2/convolve.svg
    old/cop2/cornerramp.svg
    old/cop2/crop.svg
    old/cop2/defocus.svg
    old/cop2/deform.svg
    old/cop2/degrain.svg
    old/cop2/deinterlace.svg
    old/cop2/delete.svg
    old/cop2/diff.svg
    old/cop2/dilateerode.svg
    old/cop2/dof.svg
    old/cop2/edge.svg
    old/cop2/emboss.svg
    old/cop2/env.svg
    old/cop2/equalize.svg
    old/cop2/expand.svg
    old/cop2/extend.svg
    old/cop2/fetch.svg
    old/cop2/fieldmerge.svg
    old/cop2/fieldsplit.svg
    old/cop2/fieldswap.svg
    old/cop2/file.svg
    old/cop2/flip.svg
    old/cop2/fog.svg
    old/cop2/font.svg
    old/cop2/frontface.svg
    old/cop2/function.svg
    old/cop2/gamma.svg
    old/cop2/geokey.svg
    old/cop2/geometry.svg
    old/cop2/gradient.svg
    old/cop2/grain.svg
    old/cop2/hsv.svg
    old/cop2/huecurve.svg
    old/cop2/illpixel.svg
    old/cop2/inside.svg
    old/cop2/invert.svg
    old/cop2/layer.svg
    old/cop2/levels.svg
    old/cop2/light.svg
    old/cop2/limit.svg
    old/cop2/lookup.svg
    old/cop2/lumakey.svg
    old/cop2/mask.svg
    old/cop2/max.svg
    old/cop2/median.svg
    old/cop2/merge.svg
    old/cop2/min.svg
    old/cop2/mono.svg
    old/cop2/mosaic.svg
    old/cop2/multiply.svg
    old/cop2/noise.svg
    old/cop2/null.svg
    old/cop2/outside.svg
    old/cop2/over.svg
    old/cop2/pin.svg
    old/cop2/pixel.svg
    old/cop2/premultiply.svg
    old/cop2/pulldown.svg
    old/cop2/pushup.svg
    old/cop2/quantize.svg
    old/cop2/radialblur.svg
    old/cop2/ramp.svg
    old/cop2/reference.svg
    old/cop2/rename.svg
    old/cop2/render.svg
    old/cop2/reverse.svg
    old/cop2/rotoshape.svg
    old/cop2/rotospline.svg
    old/cop2/scale.svg
    old/cop2/screen.svg
    old/cop2/screenkey.svg
    old/cop2/sequence.svg
    old/cop2/shape.svg
    old/cop2/sharpen.svg
    old/cop2/shift.svg
    old/cop2/shuffle.svg
    old/cop2/snip.svg
    old/cop2/still.svg
    old/cop2/streak.svg
    old/cop2/subnet.svg
    old/cop2/subtract.svg
    old/cop2/swap.svg
    old/cop2/switch.svg
    old/cop2/system.svg
    old/cop2/tile.svg
    old/cop2/tima.svg
    old/cop2/timefilter.svg
    old/cop2/timescale.svg
    old/cop2/translate.svg
    old/cop2/trim.svg
    old/cop2/under.svg
    old/cop2/unpin.svg
    old/cop2/uvmap.svg
    old/cop2/vector.svg
    old/cop2/velblur.svg
    old/cop2/vex.svg
    old/cop2/vexfilter.svg
    old/cop2/vexgenerate.svg
    old/cop2/warp.svg
    old/cop2/window.svg
    old/cop2/wipe.svg
    old/cop2/xform.svg
    old/cop2/xor.svg
    old/cop2/zcomp.svg
    old/dop/activevalue.svg
    old/dop/affector.svg
    old/dop/anchoralignaxis.svg
    old/dop/anchorobjpointidpos.svg
    old/dop/anchorobjpointidrot.svg
    old/dop/anchorobjpointnumpos.svg
    old/dop/anchorobjpointnumrot.svg
    old/dop/anchorobjprimpos.svg
    old/dop/anchorobjspacepos.svg
    old/dop/anchorobjspacerot.svg
    old/dop/anchorworldspacepos.svg
    old/dop/anchorworldspacerot.svg
    old/dop/applydata.svg
    old/dop/blendfactor.svg
    old/dop/blendsolver.svg
    old/dop/clothclothcollider.svg
    old/dop/clothconstraint.svg
    old/dop/clothexplicitint.svg
    old/dop/clothforces.svg
    old/dop/clothhybridint.svg
    old/dop/clothimplicitint.svg
    old/dop/clothobject.svg
    old/dop/clothphysparms.svg
    old/dop/clothsolver.svg
    old/dop/clothsolvercontrol.svg
    old/dop/clothstitchconstraint.svg
    old/dop/clothvisualization.svg
    old/dop/clothvolumecollider.svg
    old/dop/colliderlabel.svg
    old/dop/conrelationship.svg
    old/dop/constraint.svg
    old/dop/container.svg
    old/dop/copydata.svg
    old/dop/copyobject.svg
    old/dop/copysolver.svg
    old/dop/delete.svg
    old/dop/drag.svg
    old/dop/emptydata.svg
    old/dop/emptyobject.svg
    old/dop/fan.svg
    old/dop/fetchdata.svg
    old/dop/fieldforce.svg
    old/dop/file.svg
    old/dop/filedata.svg
    old/dop/geometrycopy.svg
    old/dop/gravity.svg
    old/dop/groundplane.svg
    old/dop/group.svg
    old/dop/hardconrel.svg
    old/dop/instancedobject.svg
    old/dop/magnetforce.svg
    old/dop/merge.svg
    old/dop/modifydata.svg
    old/dop/motion.svg
    old/dop/multisolver.svg
    old/dop/nocollider.svg
    old/dop/noconrel.svg
    old/dop/noise.svg
    old/dop/objpos.svg
    old/dop/partition.svg
    old/dop/physparms.svg
    old/dop/pointcollider.svg
    old/dop/pointforce.svg
    old/dop/pointmapping.svg
    old/dop/pointpos.svg
    old/dop/popobject.svg
    old/dop/popshapematch.svg
    old/dop/popsolver.svg
    old/dop/position.svg
    old/dop/rbdconfigureobject.svg
    old/dop/rbdconstraint.svg
    old/dop/rbdfracturedobject.svg
    old/dop/rbdglueobject.svg
    old/dop/rbdkeyactive.svg
    old/dop/rbdobject.svg
    old/dop/rbdpointobject.svg
    old/dop/rbdrotconstraint.svg
    old/dop/rbdsolver.svg
    old/dop/rbdstate.svg
    old/dop/rbdvisualization.svg
    old/dop/renderparms.svg
    old/dop/scriptsolver.svg
    old/dop/sopgeo.svg
    old/dop/sopsolver.svg
    old/dop/sphereedgetree.svg
    old/dop/spherepointtree.svg
    old/dop/split.svg
    old/dop/springconrel.svg
    old/dop/staticsolver.svg
    old/dop/subnet.svg
    old/dop/switch.svg
    old/dop/switchsolver.svg
    old/dop/switchvalue.svg
    old/dop/thinplatecollider.svg
    old/dop/twostateconrel.svg
    old/dop/uniformforce.svg
    old/dop/volume.svg
    old/dop/volumecollider.svg
    old/dop/vortexforce.svg
    old/dop/wireconfigureobject.svg
    old/dop/wireforcemodel.svg
    old/dop/wireglueconstraint.svg
    old/dop/wireobject.svg
    old/dop/wirephysparms.svg
    old/dop/wiresolver.svg
    old/dop/wirevisualization.svg
    old/dop/wirevolumecollider.svg
    old/dop/wirewirecollider.svg
    old/obj/ambient.svg
    old/obj/blend.svg
    old/obj/bone.svg
    old/obj/cam.svg
    old/obj/dopnet.svg
    old/obj/fetch.svg
    old/obj/fog.svg
    old/obj/force.svg
    old/obj/geo.svg
    old/obj/handle.svg
    old/obj/joints.svg
    old/obj/light.svg
    old/obj/microphone.svg
    old/obj/null.svg
    old/obj/opfilter.svg
    old/obj/opgroup.svg
    old/obj/path.svg
    old/obj/pathcv.svg
    old/obj/pickblend.svg
    old/obj/pickbone.svg
    old/obj/pickcam.svg
    old/obj/pickgeo.svg
    old/obj/picklight.svg
    old/obj/picknull.svg
    old/obj/pickother.svg
    old/obj/render.svg
    old/obj/rivet.svg
    old/obj/selectabove.svg
    old/obj/selectall.svg
    old/obj/selectbelow.svg
    old/obj/selectsubnet.svg
    old/obj/sound.svg
    old/obj/sticky.svg
    old/obj/subnet.svg
    old/obj/switcher.svg
    old/out/alfred.svg
    old/out/amazon.svg
    old/out/archive.svg
    old/out/batch.svg
    old/out/channel.svg
    old/out/code.svg
    old/out/codedata.svg
    old/out/comp.svg
    old/out/cop.svg
    old/out/dop.svg
    old/out/framedep.svg
    old/out/geometry.svg
    old/out/image3d.svg
    old/out/mantra.svg
    old/out/mental.svg
    old/out/merge.svg
    old/out/movie.svg
    old/out/multihost.svg
    old/out/ogl.svg
    old/out/opgroup.svg
    old/out/rman.svg
    old/out/scene.svg
    old/out/shell.svg
    old/out/subnet.svg
    old/out/switch.svg
    old/out/wren.svg
    old/pop/acceleration.svg
    old/pop/age.svg
    old/pop/angvelocity.svg
    old/pop/app.svg
    old/pop/attractor.svg
    old/pop/attribtransfer.svg
    old/pop/attribute.svg
    old/pop/code.svg
    old/pop/collect.svg
    old/pop/collision.svg
    old/pop/color.svg
    old/pop/creep.svg
    old/pop/drag.svg
    old/pop/event.svg
    old/pop/fan.svg
    old/pop/fetch.svg
    old/pop/fireworks.svg
    old/pop/follow.svg
    old/pop/force.svg
    old/pop/group.svg
    old/pop/hitinfo.svg
    old/pop/instance.svg
    old/pop/interact.svg
    old/pop/kill.svg
    old/pop/limit.svg
    old/pop/lineage.svg
    old/pop/location.svg
    old/pop/lookat.svg
    old/pop/null.svg
    old/pop/opgroup.svg
    old/pop/orbit.svg
    old/pop/position.svg
    old/pop/property.svg
    old/pop/proximity.svg
    old/pop/rbdconstrain.svg
    old/pop/rbdcreate.svg
    old/pop/rbdunify.svg
    old/pop/render.svg
    old/pop/resistance.svg
    old/pop/rotation.svg
    old/pop/softbody.svg
    old/pop/softlimit.svg
    old/pop/source.svg
    old/pop/speedlimit.svg
    old/pop/split.svg
    old/pop/sprite.svg
    old/pop/state.svg
    old/pop/stream.svg
    old/pop/subnet.svg
    old/pop/suppress.svg
    old/pop/switch.svg
    old/pop/torque.svg
    old/pop/translation.svg
    old/pop/turn.svg
    old/pop/upvector.svg
    old/pop/velocity.svg
    old/pop/vex.svg
    old/pop/wind.svg
    old/shop/app.svg
    old/shop/background.svg
    old/shop/bumpy.svg
    old/shop/clay.svg
    old/shop/constant.svg
    old/shop/contour.svg
    old/shop/displace.svg
    old/shop/emitter.svg
    old/shop/fog.svg
    old/shop/generic.svg
    old/shop/geometry.svg
    old/shop/gingham.svg
    old/shop/glass.svg
    old/shop/hair.svg
    old/shop/image3d.svg
    old/shop/lens.svg
    old/shop/light.svg
    old/shop/matte.svg
    old/shop/nothumb.svg
    old/shop/output.svg
    old/shop/photon.svg
    old/shop/photonvol.svg
    old/shop/polka.svg
    old/shop/select.svg
    old/shop/shadow.svg
    old/shop/subnet.svg
    old/shop/surface.svg
    old/shop/surfaceshadow.svg
    old/shop/switch.svg
    old/shop/water.svg
    old/sop/add.svg
    old/sop/align.svg
    old/sop/arm.svg
    old/sop/attribcomposite.svg
    old/sop/attribcopy.svg
    old/sop/attribcreate.svg
    old/sop/attribmirror.svg
    old/sop/attribpromote.svg
    old/sop/attribstringedit.svg
    old/sop/attribtransfer.svg
    old/sop/attribute.svg
    old/sop/bakevex.svg
    old/sop/basis.svg
    old/sop/blast.svg
    old/sop/blend.svg
    old/sop/blendshapes.svg
    old/sop/bonelink.svg
    old/sop/boolean.svg
    old/sop/bound.svg
    old/sop/box.svg
    old/sop/bridge.svg
    old/sop/bulge.svg
    old/sop/cache.svg
    old/sop/cap.svg
    old/sop/capture.svg
    old/sop/capturecorrect.svg
    old/sop/captureedit.svg
    old/sop/capturelayerpaint.svg
    old/sop/capturemeta.svg
    old/sop/capturemirror.svg
    old/sop/captureoverride.svg
    old/sop/capturepaint.svg
    old/sop/captureproximity.svg
    old/sop/carve.svg
    old/sop/channel.svg
    old/sop/circle.svg
    old/sop/clay.svg
    old/sop/clip.svg
    old/sop/clothcreateseam.svg
    old/sop/clothmatchpanels.svg
    old/sop/clothmatchseams.svg
    old/sop/clothrefine.svg
    old/sop/comb.svg
    old/sop/connectivity.svg
    old/sop/control.svg
    old/sop/convert.svg
    old/sop/convertmeta.svg
    old/sop/cookie.svg
    old/sop/copy.svg
    old/sop/crease.svg
    old/sop/creep.svg
    old/sop/cregion.svg
    old/sop/curve.svg
    old/sop/curveclay.svg
    old/sop/curvesect.svg
    old/sop/deform.svg
    old/sop/deformmeta.svg
    old/sop/delete.svg
    old/sop/delta.svg
    old/sop/disk.svg
    old/sop/dissolve.svg
    old/sop/divide.svg
    old/sop/doptransform.svg
    old/sop/duplicate.svg
    old/sop/edgecollapse.svg
    old/sop/edgecusp.svg
    old/sop/edgedivide.svg
    old/sop/edgeflip.svg
    old/sop/edit.svg
    old/sop/ends.svg
    old/sop/extrude.svg
    old/sop/facet.svg
    old/sop/file.svg
    old/sop/fillet.svg
    old/sop/fit.svg
    old/sop/fold.svg
    old/sop/font.svg
    old/sop/force.svg
    old/sop/fractal.svg
    old/sop/fuse.svg
    old/sop/grid.svg
    old/sop/group.svg
    old/sop/groupcopy.svg
    old/sop/grouptransfer.svg
    old/sop/hole.svg
    old/sop/inflate.svg
    old/sop/iso.svg
    old/sop/isooffset.svg
    old/sop/join.svg
    old/sop/joint.svg
    old/sop/lattice.svg
    old/sop/layer.svg
    old/sop/leg.svg
    old/sop/limb.svg
    old/sop/line.svg
    old/sop/lod.svg
    old/sop/lsystem.svg
    old/sop/magnet.svg
    old/sop/matchtopology.svg
    old/sop/measure.svg
    old/sop/merge.svg
    old/sop/metaball.svg
    old/sop/metasquad.svg
    old/sop/mirror.svg
    old/sop/model.svg
    old/sop/network.svg
    old/sop/null.svg
    old/sop/object.svg
    old/sop/object_merge.svg
    old/sop/opgroup.svg
    old/sop/paint.svg
    old/sop/particle.svg
    old/sop/partition.svg
    old/sop/paste.svg
    old/sop/peak.svg
    old/sop/platonic.svg
    old/sop/point.svg
    old/sop/polybevel.svg
    old/sop/polycap.svg
    old/sop/polyextrude.svg
    old/sop/polygon.svg
    old/sop/polyknit.svg
    old/sop/polyloft.svg
    old/sop/polypatch.svg
    old/sop/polyreduce.svg
    old/sop/polyspline.svg
    old/sop/polysplit.svg
    old/sop/polystitch.svg
    old/sop/polywire.svg
    old/sop/pop.svg
    old/sop/primitive.svg
    old/sop/primitivesplit.svg
    old/sop/profile.svg
    old/sop/project.svg
    old/sop/rails.svg
    old/sop/ray.svg
    old/sop/refine.svg
    old/sop/resample.svg
    old/sop/rest.svg
    old/sop/reverse.svg
    old/sop/revolve.svg
    old/sop/rishader.svg
    old/sop/round.svg
    old/sop/sblend.svg
    old/sop/scatter.svg
    old/sop/sculpt.svg
    old/sop/shop.svg
    old/sop/skeleton.svg
    old/sop/skin.svg
    old/sop/smooth.svg
    old/sop/snap.svg
    old/sop/softpeak.svg
    old/sop/softxform.svg
    old/sop/sort.svg
    old/sop/sphere.svg
    old/sop/spring.svg
    old/sop/starburst.svg
    old/sop/stitch.svg
    old/sop/subdivide.svg
    old/sop/subnet.svg
    old/sop/superquad.svg
    old/sop/surfsect.svg
    old/sop/sweep.svg
    old/sop/switch.svg
    old/sop/texture.svg
    old/sop/torus.svg
    old/sop/trace.svg
    old/sop/trail.svg
    old/sop/transform.svg
    old/sop/triangulate2d.svg
    old/sop/tribez.svg
    old/sop/tridivide.svg
    old/sop/trim.svg
    old/sop/tristrip.svg
    old/sop/tube.svg
    old/sop/turbulence.svg
    old/sop/twist.svg
    old/sop/unix.svg
    old/sop/unpaste.svg
    old/sop/uvbrush.svg
    old/sop/uvedit.svg
    old/sop/uvfuse.svg
    old/sop/uvpelt.svg
    old/sop/uvproject.svg
    old/sop/uvtransform.svg
    old/sop/uvunwrap.svg
    old/sop/vertex.svg
    old/sop/vertexsplit.svg
    old/sop/vex.svg
    old/sop/visibility.svg
    old/sop/wire.svg
    old/sop/wirecapture.svg
    old/sop/wiredeform.svg
    old/sop/xform.svg
    old/sop/xformaxis.svg
    old/vopnet/app.svg
    old/vopnet/chop.svg
    old/vopnet/cop2filter.svg
    old/vopnet/cop2gen.svg
    old/vopnet/displace.svg
    old/vopnet/fog.svg
    old/vopnet/image3d.svg
    old/vopnet/light.svg
    old/vopnet/photon.svg
    old/vopnet/pop.svg
    old/vopnet/rsl_displace.svg
    old/vopnet/rsl_light.svg
    old/vopnet/rsl_surface.svg
    old/vopnet/rsl_volume.svg
    old/vopnet/shadow.svg
    old/vopnet/sop.svg
    old/vopnet/subnet.svg
    old/vopnet/surface.svg
    PANETYPES/bundle_list.svg
    PANETYPES/channel_list.svg
    PANETYPES/channels_dopesheet.svg
    PANETYPES/channels_graph.svg
    PANETYPES/channels_spreadsheet.svg
    PANETYPES/custom.svg
    PANETYPES/datatree_lightbank.svg
    PANETYPES/datatree_objectappearance.svg
    PANETYPES/details.svg
    PANETYPES/handle_list.svg
    PANETYPES/help_browser.svg
    PANETYPES/ipr.svg
    PANETYPES/linker.svg
    PANETYPES/network.svg
    PANETYPES/parameter_spreadsheet.svg
    PANETYPES/parameters.svg
    PANETYPES/python_shell.svg
    PANETYPES/take_list.svg
    PANETYPES/textport.svg
    PANETYPES/tree.svg
    PANETYPES/viewer_3D.svg
    PANETYPES/viewer_chops.svg
    PANETYPES/viewer_cop.svg
    PARTS/attributes_lg.svg
    PARTS/attributes_med.svg
    PARTS/attributes_sm.svg
    PARTS/brush.svg
    PARTS/calculator.svg
    PARTS/color.svg
    PARTS/Colorwheel.svg
    PARTS/constraint.svg
    PARTS/delete_circle.svg
    PARTS/delete_x.svg
    PARTS/fluids.svg
    PARTS/glue.svg
    PARTS/image.svg
    PARTS/magnet.svg
    PARTS/move_arrow.svg
    PARTS/particle.svg
    PARTS/polygon.svg
    PARTS/polygon_sphere.svg
    PARTS/polygon_sphere_cusp.svg
    PARTS/polygons_2.svg
    PARTS/polygons_4.svg
    PARTS/polygons_cube.svg
    PARTS/polygons_mesh.svg
    PARTS/rbd.svg
    PARTS/snowflake.svg
    PARTS/solver.svg
    PLAYBAR/audio.svg
    PLAYBAR/editable_keys.svg
    PLAYBAR/frame_first.svg
    PLAYBAR/frame_next.svg
    PLAYBAR/frame_prev.svg
    PLAYBAR/keyframe_next.svg
    PLAYBAR/keyframe_prev.svg
    PLAYBAR/last_frame.svg
    PLAYBAR/pause.svg
    PLAYBAR/play_backward.svg
    PLAYBAR/play_forward.svg
    PLAYBAR/play_loop.svg
    PLAYBAR/play_once.svg
    PLAYBAR/play_zigzag.svg
    PLAYBAR/realtime.svg
    PLAYBAR/record.svg
    PLAYBAR/record_dark.svg
    PLAYBAR/record_light.svg
    PLAYBAR/set_key.svg
    PLAYBAR/stop.svg
    POP/acceleration.svg
    POP/advectbyvolumes.svg
    POP/age.svg
    POP/angvelocity.svg
    POP/attractor.svg
    POP/attribtransfer.svg
    POP/attribute.svg
    POP/awaken.svg
    POP/collect.svg
    POP/collision.svg
    POP/color.svg
    POP/creep.svg
    POP/curlnoise.svg
    POP/drag.svg
    POP/fan.svg
    POP/fetch.svg
    POP/fireworks.svg
    POP/follow.svg
    POP/force.svg
    POP/gravity.svg
    POP/group.svg
    POP/hitinfo.svg
    POP/instance.svg
    POP/interact.svg
    POP/kill.svg
    POP/limit.svg
    POP/lineage.svg
    POP/location.svg
    POP/lookat.svg
    POP/orbit.svg
    POP/position.svg
    POP/property.svg
    POP/proximity.svg
    POP/render.svg
    POP/resistance.svg
    POP/rotation.svg
    POP/sleep.svg
    POP/softlimit.svg
    POP/source.svg
    POP/speedlimit.svg
    POP/split.svg
    POP/sprite.svg
    POP/stream.svg
    POP/torque.svg
    POP/translation.svg
    POP/turn.svg
    POP/upvector.svg
    POP/velocity.svg
    POP/wind.svg
    PRIMITIVES/alembicref.svg
    PRIMITIVES/beziercurve.svg
    PRIMITIVES/beziermesh.svg
    PRIMITIVES/circle.svg
    PRIMITIVES/mesh.svg
    PRIMITIVES/metaball.svg
    PRIMITIVES/null.svg
    PRIMITIVES/nurbscurve.svg
    PRIMITIVES/nurbsmesh.svg
    PRIMITIVES/packedagent.svg
    PRIMITIVES/packeddisk.svg
    PRIMITIVES/packedfragment.svg
    PRIMITIVES/packedgeometry.svg
    PRIMITIVES/pastesurf.svg
    PRIMITIVES/poly.svg
    PRIMITIVES/polysoup.svg
    PRIMITIVES/sphere.svg
    PRIMITIVES/tetrahedron.svg
    PRIMITIVES/tube.svg
    PRIMITIVES/vdb.svg
    PRIMITIVES/volume.svg
    ROP/alfred.svg
    ROP/archive.svg
    ROP/batch.svg
    ROP/brickmap.svg
    ROP/dsmmerge.svg
    ROP/fbx.svg
    ROP/framecontainer.svg
    ROP/framedep.svg
    ROP/image3d.svg
    ROP/mantra.svg
    ROP/netbarrier.svg
    ROP/opengl.svg
    ROP/prepost.svg
    ROP/rman.svg
    ROP/shell.svg
    ROP/soho.svg
    ROP/vm_geo_sprite.svg
    ROP/wedge.svg
    ROP/wren.svg
    SHELF/addfield.svg
    SHELF/agents_follow_path.svg
    SHELF/atmosphere.svg
    SHELF/attach_constraint_animation.svg
    SHELF/attach_constraint_dynamicspoint.svg
    SHELF/attach_constraint_rbd.svg
    SHELF/attach_wire_to_surface.svg
    SHELF/attractfluid.svg
    SHELF/bake_character.svg
    SHELF/basic_rbd.svg
    SHELF/beach_tank.svg
    SHELF/boolean_intersect.svg
    SHELF/boolean_subtract.svg
    SHELF/boolean_union.svg
    SHELF/box_fire.svg
    SHELF/box_flamefront.svg
    SHELF/box_fluid.svg
    SHELF/box_smoke.svg
    SHELF/candle.svg
    SHELF/center_pivot.svg
    SHELF/clear_texture_cache.svg
    SHELF/cloth_follow_animation.svg
    SHELF/clothpinconstraint.svg
    SHELF/clothspringconstraint.svg
    SHELF/cloudrig.svg
    SHELF/clouds.svg
    SHELF/collision.svg
    SHELF/combine_objects.svg
    SHELF/contrail.svg
    SHELF/convert_to_fire.svg
    SHELF/convert_to_fluid.svg
    SHELF/convert_to_fuel.svg
    SHELF/convert_to_lava.svg
    SHELF/convert_to_particlefluid.svg
    SHELF/convert_to_particlegrain.svg
    SHELF/convert_to_smoke.svg
    SHELF/cool_within_object.svg
    SHELF/create_rig.svg
    SHELF/crowd.svg
    SHELF/curve_draw.svg
    SHELF/curve_nurbs.svg
    SHELF/curve_poly.svg
    SHELF/curveattract.svg
    SHELF/debris.svg
    SHELF/deforming_object.svg
    SHELF/dentableobject.svg
    SHELF/detach_constraint.svg
    SHELF/distribute_fluid_sim.svg
    SHELF/distribute_particle_fluid_sim.svg
    SHELF/dry_ice.svg
    SHELF/dry_sand.svg
    SHELF/edgeloop.svg
    SHELF/elasticobject.svg
    SHELF/emit_steam.svg
    SHELF/equalizer.svg
    SHELF/expand_from_objects.svg
    SHELF/exploding_object.svg
    SHELF/explosion.svg
    SHELF/extract_object.svg
    SHELF/factory.svg
    SHELF/find_material.svg
    SHELF/fire.svg
    SHELF/fireball.svg
    SHELF/flame_thrower.svg
    SHELF/flat_tank.svg
    SHELF/flip_tank.svg
    SHELF/flipmist.svg
    SHELF/flower.svg
    SHELF/fluid_pump.svg
    SHELF/fluid_sink.svg
    SHELF/fluid_source.svg
    SHELF/fog.svg
    SHELF/followpath.svg
    SHELF/footprints.svg
    SHELF/freezetransforms.svg
    SHELF/fuel_from_texture.svg
    SHELF/grass.svg
    SHELF/hair.svg
    SHELF/hairstyle.svg
    SHELF/headphones.svg
    SHELF/heat_within_object.svg
    SHELF/hide.svg
    SHELF/jellyfish.svg
    SHELF/knife.svg
    SHELF/lookat.svg
    SHELF/lookup.svg
    SHELF/make_collision.svg
    SHELF/makebreakable.svg
    SHELF/melt.svg
    SHELF/motion_capture.svg
    SHELF/move_with_fluid.svg
    SHELF/ocean.svg
    SHELF/oceanwaves.svg
    SHELF/paint_fuel.svg
    SHELF/paint_temperature.svg
    SHELF/painttearable.svg
    SHELF/parent.svg
    SHELF/parent_constraint.svg
    SHELF/pointattract.svg
    SHELF/poselibrary.svg
    SHELF/pour.svg
    SHELF/pyrocluster.svg
    SHELF/rain.svg
    SHELF/rbd_activate.svg
    SHELF/rbd_deactivate.svg
    SHELF/rbd_grains.svg
    SHELF/reconnect_part.svg
    SHELF/remove_from_simulation.svg
    SHELF/river.svg
    SHELF/robot.svg
    SHELF/sand_sheet.svg
    SHELF/sand_strand.svg
    SHELF/sand_upres.svg
    SHELF/sandbox.svg
    SHELF/sbdattachmentconstraint.svg
    SHELF/sculptedparticlefluid.svg
    SHELF/seedvorticles.svg
    SHELF/shadow.svg
    SHELF/smoke_heavy.svg
    SHELF/smoke_wispy.svg
    SHELF/smokecluster.svg
    SHELF/snow.svg
    SHELF/source_from_points.svg
    SHELF/source_from_surface.svg
    SHELF/source_from_volume.svg
    SHELF/sparks.svg
    SHELF/splash.svg
    SHELF/splash_tank.svg
    SHELF/squid.svg
    SHELF/teapot.svg
    SHELF/tearableobject.svg
    SHELF/temperature_from_texture.svg
    SHELF/tree_branch.svg
    SHELF/tree_conifer.svg
    SHELF/tree_deciduous.svg
    SHELF/tree_leaf.svg
    SHELF/tree_roots.svg
    SHELF/tree_seed.svg
    SHELF/tree_trunk.svg
    SHELF/turntable.svg
    SHELF/twist_bend.svg
    SHELF/twist_linear_taper.svg
    SHELF/twist_shear.svg
    SHELF/twist_squashstretch.svg
    SHELF/twist_taper.svg
    SHELF/twist_twist.svg
    SHELF/underwater_bubbles.svg
    SHELF/unparent.svg
    SHELF/volcano.svg
    SHELF/volcano_smoke.svg
    SHELF/volumelight.svg
    SHELF/vortex_from_curve.svg
    SHELF/wave.svg
    SHELF/wave_layer_tank.svg
    SHELF/wave_tank.svg
    SHELF/wet_sand.svg
    SHELF/whitecaps.svg
    SHELF/whitewater.svg
    SHELF/wind_force.svg
    SHELF/wire_attach_constraint_animation.svg
    SHELF/wire_attach_constraint_point.svg
    SHELF/wire_attach_constraint_rbd.svg
    SHELF/wire_detach_constraint.svg
    SHELF/wire_initial_pose.svg
    SHELF/wirepinconstraint.svg
    SHELF/wirespringconstraint.svg
    SHOP/material.svg
    SHOP/select.svg
    SHOP/surface.svg
    SHOP/tooncolorshader.svg
    SHOP/toonoutlineshader.svg
    SHOP/v_decal.svg
    SHOP/v_plastic.svg
    SHOP/vm_geo_file.svg
    SHOP/vopfog.svg
    SHOP/voplight.svg
    SHOP/vopmaterial.svg
    SHOP/vopsurface.svg
    SOP/add.svg
    SOP/agentcollisionlayer.svg
    SOP/agentconfigurejoints.svg
    SOP/agentconstraintnetwork.svg
    SOP/alembic.svg
    SOP/align.svg
    SOP/assemble.svg
    SOP/attribcast.svg
    SOP/attribcomposite.svg
    SOP/attribcopy.svg
    SOP/attribcreate.svg
    SOP/attribfade.svg
    SOP/attribfromvolume.svg
    SOP/attribinterpolate.svg
    SOP/attribmirror.svg
    SOP/attribpromote.svg
    SOP/attribrandomize.svg
    SOP/attribreorient.svg
    SOP/attribstringedit.svg
    SOP/attribtransfer.svg
    SOP/attribute.svg
    SOP/attribvop.svg
    SOP/attribwrangle.svg
    SOP/bakevolume.svg
    SOP/basis.svg
    SOP/blast.svg
    SOP/blendshapes.svg
    SOP/block_begin.svg
    SOP/block_end.svg
    SOP/bonelink.svg
    SOP/bound.svg
    SOP/box.svg
    SOP/break.svg
    SOP/bridge.svg
    SOP/bulge.svg
    SOP/cap.svg
    SOP/capture.svg
    SOP/capturecorrect.svg
    SOP/capturemeta.svg
    SOP/capturemirror.svg
    SOP/captureoverride.svg
    SOP/captureproximity.svg
    SOP/carve.svg
    SOP/circle.svg
    SOP/clay.svg
    SOP/clean.svg
    SOP/clip.svg
    SOP/clothcapture.svg
    SOP/clothcreateseam.svg
    SOP/clothdeform.svg
    SOP/clothrefine.svg
    SOP/cloud.svg
    SOP/cloudlight.svg
    SOP/cloudnoise.svg
    SOP/cluster.svg
    SOP/clusterpoints.svg
    SOP/color.svg
    SOP/comb.svg
    SOP/cone.svg
    SOP/connectadjacentpieces.svg
    SOP/connectivity.svg
    SOP/convert.svg
    SOP/convertmeta.svg
    SOP/convertvdb.svg
    SOP/convertvolume.svg
    SOP/cookie.svg
    SOP/copy.svg
    SOP/crease.svg
    SOP/creep.svg
    SOP/cregion.svg
    SOP/curve.svg
    SOP/curveclay.svg
    SOP/curvesect.svg
    SOP/deform.svg
    SOP/deformmeta.svg
    SOP/deformmuscle.svg
    SOP/dissolve.svg
    SOP/divide.svg
    SOP/dopimport.svg
    SOP/dopimportrecords.svg
    SOP/drawcurve.svg
    SOP/drawhair.svg
    SOP/duplicate.svg
    SOP/each.svg
    SOP/edgecollapse.svg
    SOP/edgecusp.svg
    SOP/edgedivide.svg
    SOP/edgeflip.svg
    SOP/edit.svg
    SOP/ends.svg
    SOP/enumerate.svg
    SOP/explodedview.svg
    SOP/extrude.svg
    SOP/extrudevolume.svg
    SOP/facet.svg
    SOP/fillet.svg
    SOP/finalizewaves.svg
    SOP/findshortestpath.svg
    SOP/fit.svg
    SOP/fluidcompress.svg
    SOP/font.svg
    SOP/force.svg
    SOP/foreach.svg
    SOP/fractal.svg
    SOP/fur.svg
    SOP/fuse.svg
    SOP/grid.svg
    SOP/group.svg
    SOP/groupcopy.svg
    SOP/grouppaint.svg
    SOP/grouptransfer.svg
    SOP/hole.svg
    SOP/inflate.svg
    SOP/instance.svg
    SOP/iso.svg
    SOP/isooffset.svg
    SOP/join.svg
    SOP/lattice.svg
    SOP/layer.svg
    SOP/line.svg
    SOP/loadslices.svg
    SOP/lod.svg
    SOP/loft.svg
    SOP/lsystem.svg
    SOP/magnet.svg
    SOP/matchaxis.svg
    SOP/matchsize.svg
    SOP/material.svg
    SOP/mdd.svg
    SOP/measure.svg
    SOP/merge.svg
    SOP/metaball.svg
    SOP/metagroups.svg
    SOP/mirror.svg
    SOP/mountain.svg
    SOP/name.svg
    SOP/network.svg
    SOP/normal.svg
    SOP/object_merge.svg
    SOP/pack.svg
    SOP/packededit.svg
    SOP/paint.svg
    SOP/paintcolorvolume.svg
    SOP/paintfogvolume.svg
    SOP/paintsdfvolume.svg
    SOP/particle.svg
    SOP/particlefluidsurface.svg
    SOP/partition.svg
    SOP/paste.svg
    SOP/peak.svg
    SOP/platonic.svg
    SOP/point.svg
    SOP/pointcloudiso.svg
    SOP/pointdeform.svg
    SOP/pointgenerate.svg
    SOP/pointjitter.svg
    SOP/pointreplicate.svg
    SOP/pointsfromvolume.svg
    SOP/pointwrangle.svg
    SOP/polybevel.svg
    SOP/polybridge.svg
    SOP/polycap.svg
    SOP/polycut.svg
    SOP/polydoctor.svg
    SOP/polyexpand2d.svg
    SOP/polyextrude.svg
    SOP/polyframe.svg
    SOP/polyknit.svg
    SOP/polyloft.svg
    SOP/polypatch.svg
    SOP/polyreduce.svg
    SOP/polysoup.svg
    SOP/polyspline.svg
    SOP/polysplit.svg
    SOP/polystitch.svg
    SOP/polywire.svg
    SOP/pop.svg
    SOP/primitive.svg
    SOP/primitivesplit.svg
    SOP/profile.svg
    SOP/project.svg
    SOP/rails.svg
    SOP/ray.svg
    SOP/refine.svg
    SOP/relax.svg
    SOP/remesh.svg
    SOP/repack.svg
    SOP/resample.svg
    SOP/rest.svg
    SOP/reverse.svg
    SOP/revolve.svg
    SOP/ripple.svg
    SOP/rishader.svg
    SOP/round.svg
    SOP/sblend.svg
    SOP/scatter.svg
    SOP/script.svg
    SOP/sculpt.svg
    SOP/shatter.svg
    SOP/shop.svg
    SOP/shrinkwrap.svg
    SOP/skin.svg
    SOP/sky.svg
    SOP/slidemodifierpaint.svg
    SOP/smooth.svg
    SOP/softpeak.svg
    SOP/softxform.svg
    SOP/solid.svg
    SOP/solidfracture.svg
    SOP/solidify.svg
    SOP/solver.svg
    SOP/sphere.svg
    SOP/splicevolume.svg
    SOP/spraypaint.svg
    SOP/spring.svg
    SOP/stitch.svg
    SOP/stroke.svg
    SOP/subdivide.svg
    SOP/surfsect.svg
    SOP/sweep.svg
    SOP/testgeometry_pighead.svg
    SOP/testgeometry_rubbertoy.svg
    SOP/testgeometry_squab.svg
    SOP/tetrahedralize.svg
    SOP/tetrasurface.svg
    SOP/texture.svg
    SOP/timeblend.svg
    SOP/timeshift.svg
    SOP/topobuild.svg
    SOP/torus.svg
    SOP/trace.svg
    SOP/trail.svg
    SOP/triangulate2d.svg
    SOP/tribez.svg
    SOP/tridivide.svg
    SOP/trim.svg
    SOP/tristrip.svg
    SOP/tube.svg
    SOP/twist.svg
    SOP/unix.svg
    SOP/unpack.svg
    SOP/unpaste.svg
    SOP/uvbrush.svg
    SOP/uvedit.svg
    SOP/uvflatten.svg
    SOP/uvfuse.svg
    SOP/uvpelt.svg
    SOP/uvproject.svg
    SOP/uvquickshade.svg
    SOP/uvtransform.svg
    SOP/uvunwrap.svg
    SOP/vdbfromparticlefluid.svg
    SOP/vdbfromparticles.svg
    SOP/vdbfrompolygons.svg
    SOP/vertex.svg
    SOP/vertexsplit.svg
    SOP/visibility.svg
    SOP/visualize.svg
    SOP/volume.svg
    SOP/volumeanalysis.svg
    SOP/volumearrivaltime.svg
    SOP/volumeblur.svg
    SOP/volumebound.svg
    SOP/volumebreak.svg
    SOP/volumecompress.svg
    SOP/volumeconvolve3.svg
    SOP/volumefeather.svg
    SOP/volumefft.svg
    SOP/volumefromattrib.svg
    SOP/volumemerge.svg
    SOP/volumemix.svg
    SOP/volumeramp.svg
    SOP/volumerasterize.svg
    SOP/volumerasterizecurve.svg
    SOP/volumerasterizehair.svg
    SOP/volumerasterizeparticles.svg
    SOP/volumerasterizepoints.svg
    SOP/volumereduce.svg
    SOP/volumeresample.svg
    SOP/volumeresize.svg
    SOP/volumesdf.svg
    SOP/volumeslice.svg
    SOP/volumesplice.svg
    SOP/volumestamp.svg
    SOP/volumesurface.svg
    SOP/volumetrail.svg
    SOP/volumevelocity.svg
    SOP/volumevisualization.svg
    SOP/volumevop.svg
    SOP/volumewrangle.svg
    SOP/voronoifracture.svg
    SOP/voronoifracturepoints.svg
    SOP/voronoisplit.svg
    SOP/waveform.svg
    SOP/wire.svg
    SOP/wireblend.svg
    SOP/wirecapture.svg
    SOP/wiredeform.svg
    SOP/wiretransfershape.svg
    SOP/xform.svg
    SOP/xformaxis.svg
    SOP/xformpieces.svg
    STATUS/error.svg
    STATUS/ok.svg
    STATUS/warning.svg
    TOOLS/brush.svg
    TOOLS/dolly.svg
    TOOLS/eyedropper.svg
    TOOLS/flipbook.svg
    TOOLS/handles.svg
    TOOLS/inspect.svg
    TOOLS/move.svg
    TOOLS/render_region.svg
    TOOLS/rotate.svg
    TOOLS/scale.svg
    TOOLS/select.svg
    TOOLS/select_add.svg
    TOOLS/select_breakpoints.svg
    TOOLS/select_brush.svg
    TOOLS/select_common.svg
    TOOLS/select_component.svg
    TOOLS/select_component_brush.svg
    TOOLS/select_component_laser.svg
    TOOLS/select_component_lasso.svg
    TOOLS/select_dynamics.svg
    TOOLS/select_dynamics_modifiers.svg
    TOOLS/select_edges.svg
    TOOLS/select_facegroups.svg
    TOOLS/select_faces.svg
    TOOLS/select_groups_point.svg
    TOOLS/select_groups_pointandprimitive.svg
    TOOLS/select_groups_primitive.svg
    TOOLS/select_lasso.svg
    TOOLS/select_mode_add.svg
    TOOLS/select_mode_boxselect.svg
    TOOLS/select_mode_brush.svg
    TOOLS/select_mode_laser.svg
    TOOLS/select_mode_lasso.svg
    TOOLS/select_mode_replace.svg
    TOOLS/select_mode_subtract.svg
    TOOLS/select_mode_toggle.svg
    TOOLS/select_modifiers.svg
    TOOLS/select_objects.svg
    TOOLS/select_particles.svg
    TOOLS/select_particles_modifiers.svg
    TOOLS/select_pointgroups.svg
    TOOLS/select_points.svg
    TOOLS/select_remove.svg
    TOOLS/select_replace.svg
    TOOLS/select_vertices.svg
    TOOLS/select_visible.svg
    TOOLS/select_whole.svg
    TOOLS/snap.svg
    TOOLS/snap_curve.svg
    TOOLS/snap_grid.svg
    TOOLS/snap_point.svg
    TOOLS/tilt.svg
    TOOLS/track.svg
    TOOLS/tumble.svg
    TOOLS/view.svg
    TOOLS/zoom.svg
    VIEW/always_visible.svg
    VIEW/display_applyto_all.svg
    VIEW/display_applyto_current.svg
    VIEW/display_background.svg
    VIEW/display_construction_plane.svg
    VIEW/display_generic_scene.svg
    VIEW/display_handles.svg
    VIEW/display_hulls.svg
    VIEW/display_lock_camera.svg
    VIEW/display_objectnames_name.svg
    VIEW/display_objectnames_none.svg
    VIEW/display_objectnames_path.svg
    VIEW/display_objects.svg
    VIEW/display_particle_origins.svg
    VIEW/display_point_attribute.svg
    VIEW/display_point_coordinates.svg
    VIEW/display_point_normals.svg
    VIEW/display_point_numbers.svg
    VIEW/display_point_texture_coordinates.svg
    VIEW/display_point_velocities.svg
    VIEW/display_points.svg
    VIEW/display_primitive_normals.svg
    VIEW/display_primitive_numbers.svg
    VIEW/display_templates.svg
    VIEW/display_text.svg
    VIEW/display_vertex_grips.svg
    VIEW/display_vertex_texture_coordinates.svg
    VIEW/flat.svg
    VIEW/flat_wireframe.svg
    VIEW/hiddenline.svg
    VIEW/hiddenline_ghost.svg
    VIEW/hover_visibility.svg
    VIEW/layout_2side.svg
    VIEW/layout_2stacked.svg
    VIEW/layout_3bottom.svg
    VIEW/layout_3left.svg
    VIEW/layout_4.svg
    VIEW/layout_4bottom.svg
    VIEW/layout_4left.svg
    VIEW/layout_quad.svg
    VIEW/layout_single.svg
    VIEW/layout_tall2.svg
    VIEW/layout_tall3.svg
    VIEW/layout_tall4.svg
    VIEW/layout_viewport1.svg
    VIEW/layout_viewport2.svg
    VIEW/layout_viewport3.svg
    VIEW/layout_viewport4.svg
    VIEW/layout_wide2.svg
    VIEW/layout_wide3.svg
    VIEW/layout_wide4.svg
    VIEW/lighting_headlight.svg
    VIEW/lighting_high.svg
    VIEW/lighting_none.svg
    VIEW/lighting_normal.svg
    VIEW/lighting_objlights.svg
    VIEW/local_area_visibility.svg
    VIEW/materials.svg
    VIEW/obj_material.svg
    VIEW/selected_visibility.svg
    VIEW/shaded_bbox.svg
    VIEW/shadow_quality_high.svg
    VIEW/shadow_quality_low.svg
    VIEW/shadow_quality_medium.svg
    VIEW/shadow_quality_off.svg
    VIEW/show_all.svg
    VIEW/show_ghosted.svg
    VIEW/show_group_colors.svg
    VIEW/show_group_list.svg
    VIEW/show_one.svg
    VIEW/smooth.svg
    VIEW/smooth_wireframe.svg
    VIEW/vex.svg
    VIEW/vex_wireframe.svg
    VIEW/viewmemory.svg
    VIEW/visualization.svg
    VIEW/visualization_add_to_toolbar.svg
    VIEW/visualization_color.svg
    VIEW/visualization_global.svg
    VIEW/visualization_marker.svg
    VIEW/visualization_remove_from_toolbar.svg
    VIEW/visualization_scene.svg
    VIEW/visualization_slice.svg
    VIEW/visualization_tag.svg
    VIEW/wireframe.svg
    VIEW/wireframe_bbox.svg
    VIEW/wireframe_ghost.svg
    VOP/aanoise.svg
    VOP/abs.svg
    VOP/add.svg
    VOP/addattrib.svg
    VOP/addconst.svg
    VOP/addpoint.svg
    VOP/addprim.svg
    VOP/addsteerforce.svg
    VOP/addvertex.svg
    VOP/alphamix.svg
    VOP/ambient.svg
    VOP/and.svg
    VOP/atten.svg
    VOP/avg.svg
    VOP/banana.svg
    VOP/bind.svg
    VOP/blendregions.svg
    VOP/block_begin_for.svg
    VOP/block_begin_foreach.svg
    VOP/block_begin_if.svg
    VOP/block_end_breakif.svg
    VOP/block_end_while.svg
    VOP/boxclip.svg
    VOP/boxes.svg
    VOP/boxtile.svg
    VOP/bricker.svg
    VOP/burlap.svg
    VOP/carpaint.svg
    VOP/cavities.svg
    VOP/ceiling.svg
    VOP/cellcracks.svg
    VOP/cellnoise.svg
    VOP/clamp.svg
    VOP/collect.svg
    VOP/colormap.svg
    VOP/colormix.svg
    VOP/compare.svg
    VOP/complement.svg
    VOP/concrete.svg
    VOP/constant.svg
    VOP/copy.svg
    VOP/cosine.svg
    VOP/cross.svg
    VOP/decal_a.svg
    VOP/degtorad.svg
    VOP/depthmap.svg
    VOP/determinant.svg
    VOP/dimport.svg
    VOP/dirspacechg.svg
    VOP/displacenml.svg
    VOP/distance.svg
    VOP/divconst.svg
    VOP/divide.svg
    VOP/dot.svg
    VOP/edgefalloff.svg
    VOP/egg_shell.svg
    VOP/endswith.svg
    VOP/eulertoquat.svg
    VOP/exp.svg
    VOP/fastshadow.svg
    VOP/filtershadow.svg
    VOP/filterstep.svg
    VOP/fit.svg
    VOP/floattohmatx.svg
    VOP/floattohvec.svg
    VOP/floattoint.svg
    VOP/floattomatx.svg
    VOP/floattovec.svg
    VOP/floor.svg
    VOP/for.svg
    VOP/forpoints.svg
    VOP/frac.svg
    VOP/fresnel.svg
    VOP/fromndc.svg
    VOP/frompolar.svg
    VOP/furrows.svg
    VOP/fuzzyand.svg
    VOP/fuzzydefuzz.svg
    VOP/fuzzyinference.svg
    VOP/fuzzyinferencemirror.svg
    VOP/fuzzyinput.svg
    VOP/fuzzynot.svg
    VOP/fuzzyor.svg
    VOP/fuzzysenseobs.svg
    VOP/getobjxform.svg
    VOP/gingham.svg
    VOP/glass.svg
    VOP/global.svg
    VOP/glow.svg
    VOP/gradient3d.svg
    VOP/hasinput.svg
    VOP/hextile.svg
    VOP/hilownoise.svg
    VOP/hmatxgetcompon.svg
    VOP/hmatxsetcompon.svg
    VOP/hmatxtofloat.svg
    VOP/hsvtorgb.svg
    VOP/hvecgetcompon.svg
    VOP/hvecsetcompon.svg
    VOP/hvectofloat.svg
    VOP/hvectovec.svg
    VOP/if.svg
    VOP/ifconnected.svg
    VOP/illuminance.svg
    VOP/importattrib.svg
    VOP/ingroup.svg
    VOP/integrate3d.svg
    VOP/integrate3dclip.svg
    VOP/intersect.svg
    VOP/intersect3d.svg
    VOP/inttofloat.svg
    VOP/invert.svg
    VOP/isalpha.svg
    VOP/isconnected.svg
    VOP/isdigit.svg
    VOP/isfog.svg
    VOP/isfrontface.svg
    VOP/isshadow.svg
    VOP/length.svg
    VOP/limport.svg
    VOP/logarithm.svg
    VOP/luminance.svg
    VOP/maddconst.svg
    VOP/makexform.svg
    VOP/mandel.svg
    VOP/matte.svg
    VOP/matxgetcompon.svg
    VOP/matxsetcompon.svg
    VOP/matxtofloat.svg
    VOP/matxtoquat.svg
    VOP/max.svg
    VOP/maxcomp.svg
    VOP/metaattrib.svg
    VOP/metadensity.svg
    VOP/metaimport.svg
    VOP/metanext.svg
    VOP/metaspace.svg
    VOP/metastart.svg
    VOP/metaweight.svg
    VOP/methodcall.svg
    VOP/methodsubnet.svg
    VOP/min.svg
    VOP/mincomp.svg
    VOP/mix.svg
    VOP/modulo.svg
    VOP/mosaic.svg
    VOP/mulconst.svg
    VOP/multiply.svg
    VOP/negate.svg
    VOP/neighbour.svg
    VOP/neighbourcount.svg
    VOP/normalize.svg
    VOP/not.svg
    VOP/npoints.svg
    VOP/nrandom.svg
    VOP/objspacechg.svg
    VOP/occlusion.svg
    VOP/or.svg
    VOP/oscill.svg
    VOP/output.svg
    VOP/parameter.svg
    VOP/pbrdiffuse.svg
    VOP/pbrspecular.svg
    VOP/pcclose.svg
    VOP/pcexport.svg
    VOP/pcfarthest.svg
    VOP/pcfilter.svg
    VOP/pcimport.svg
    VOP/pciterate.svg
    VOP/pcopen.svg
    VOP/pcunshaded.svg
    VOP/periodicnoise.svg
    VOP/physicalsss.svg
    VOP/pixelarea.svg
    VOP/pixelderiv.svg
    VOP/planeclip.svg
    VOP/planecount.svg
    VOP/planeexists.svg
    VOP/planeindex.svg
    VOP/planename.svg
    VOP/planesize.svg
    VOP/pow.svg
    VOP/primattrib.svg
    VOP/primnormal.svg
    VOP/principled.svg
    VOP/print.svg
    VOP/ptexture.svg
    VOP/ptlinedistance.svg
    VOP/qmultiply.svg
    VOP/quaternion.svg
    VOP/quattomatx.svg
    VOP/radtodeg.svg
    VOP/rainbow.svg
    VOP/ramps.svg
    VOP/random.svg
    VOP/raybounce.svg
    VOP/rayhit.svg
    VOP/raytrace.svg
    VOP/rayweight.svg
    VOP/reflect.svg
    VOP/reflective.svg
    VOP/reflectlight.svg
    VOP/refract.svg
    VOP/refractlight.svg
    VOP/regex_find.svg
    VOP/regex_findall.svg
    VOP/regex_match.svg
    VOP/regex_replace.svg
    VOP/regex_split.svg
    VOP/relbbox.svg
    VOP/removepoint.svg
    VOP/removeprim.svg
    VOP/removevertex.svg
    VOP/res.svg
    VOP/restpos.svg
    VOP/rgbtohsv.svg
    VOP/rhexes.svg
    VOP/rings.svg
    VOP/rint.svg
    VOP/ripples.svg
    VOP/river.svg
    VOP/rotate.svg
    VOP/rstars.svg
    VOP/scale.svg
    VOP/scales.svg
    VOP/shadingarea.svg
    VOP/shadingderiv.svg
    VOP/shadinglayer.svg
    VOP/shadingnormal.svg
    VOP/shadow.svg
    VOP/shadowmap.svg
    VOP/shadowmatte.svg
    VOP/sign.svg
    VOP/simport.svg
    VOP/sine.svg
    VOP/slerp.svg
    VOP/smooth.svg
    VOP/softdots.svg
    VOP/spacechg.svg
    VOP/specular.svg
    VOP/splatter.svg
    VOP/sqrt.svg
    VOP/startswith.svg
    VOP/stripes.svg
    VOP/struct.svg
    VOP/structpack.svg
    VOP/structunpack.svg
    VOP/subconst.svg
    VOP/subinput.svg
    VOP/subnetconnector.svg
    VOP/subnetreturn.svg
    VOP/suboutput.svg
    VOP/subtract.svg
    VOP/surfacemodel.svg
    VOP/tangent.svg
    VOP/texture3d.svg
    VOP/texture3dbox.svg
    VOP/timing.svg
    VOP/titlecase.svg
    VOP/tolower.svg
    VOP/tondc.svg
    VOP/topolar.svg
    VOP/toupper.svg
    VOP/translate.svg
    VOP/translucent.svg
    VOP/trig.svg
    VOP/turbnoise.svg
    VOP/twotone.svg
    VOP/twoway.svg
    VOP/uvnoise.svg
    VOP/uvspacechg.svg
    VOP/vecgetcompon.svg
    VOP/vecsetcompon.svg
    VOP/vectofloat.svg
    VOP/vectohvec.svg
    VOP/veins.svg
    VOP/voronoise.svg
    VOP/waves.svg
    VOP/while.svg
    VOP/wood.svg
    VOP/worleynoise.svg
    VOP/xform.svg
    VOP/xor.svg
)
