global string $address;
$address = "//eva8400/数字动漫/三维制作中心/工作文件/10技术文件/All_mel/";

 ////////C:/Documents and Settings/youjl/My Documents/maya/7.0/scripts/

 /*


\\YOUJILIANG 的用户帐户

-------------------------------------------------------------------------------
ACTUser                  Administrator            ASPNET                   
Guest                    HelpAssistant            SQLDebugger              
SUPPORT_388945a0         
命令成功完成。





 */