# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '//10.99.1.12/数码电影/临时交换/08技术/个人文件夹/H黄帅/adv5/AdvancedSkeleton5/AdvancedSkeleton5Files/icons/otherTools.ui'
#
# Created: Tue Sep 27 15:41:12 2016
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_moreRiggingToolsWindow(object):
    def setupUi(self, moreRiggingToolsWindow):
        moreRiggingToolsWindow.setObjectName("moreRiggingToolsWindow")
        moreRiggingToolsWindow.resize(331, 363)
        moreRiggingToolsWindow.setMinimumSize(QtCore.QSize(331, 363))
        self.centralwidget = QtGui.QWidget(moreRiggingToolsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 311, 311))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.backToHairButton_6 = QtGui.QPushButton(self.frame)
        self.backToHairButton_6.setEnabled(False)
        self.backToHairButton_6.setGeometry(QtCore.QRect(210, 260, 91, 41))
        self.backToHairButton_6.setText("")
        self.backToHairButton_6.setObjectName("backToHairButton_6")
        self.buildBlendshapeButton = QtGui.QPushButton(self.frame)
        self.buildBlendshapeButton.setEnabled(True)
        self.buildBlendshapeButton.setGeometry(QtCore.QRect(210, 110, 91, 41))
        self.buildBlendshapeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/builBlendshape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buildBlendshapeButton.setIcon(icon)
        self.buildBlendshapeButton.setIconSize(QtCore.QSize(91, 41))
        self.buildBlendshapeButton.setObjectName("buildBlendshapeButton")
        self.geoCalculatorButton = QtGui.QPushButton(self.frame)
        self.geoCalculatorButton.setEnabled(True)
        self.geoCalculatorButton.setGeometry(QtCore.QRect(110, 110, 91, 41))
        self.geoCalculatorButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/geoCalculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.geoCalculatorButton.setIcon(icon1)
        self.geoCalculatorButton.setIconSize(QtCore.QSize(91, 41))
        self.geoCalculatorButton.setObjectName("geoCalculatorButton")
        self.backToHairButton_4 = QtGui.QPushButton(self.frame)
        self.backToHairButton_4.setEnabled(False)
        self.backToHairButton_4.setGeometry(QtCore.QRect(210, 160, 91, 41))
        self.backToHairButton_4.setText("")
        self.backToHairButton_4.setObjectName("backToHairButton_4")
        self.hairButton = QtGui.QPushButton(self.frame)
        self.hairButton.setGeometry(QtCore.QRect(10, 60, 91, 41))
        self.hairButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/addHair.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hairButton.setIcon(icon2)
        self.hairButton.setIconSize(QtCore.QSize(91, 41))
        self.hairButton.setObjectName("hairButton")
        self.creatSubCtrlsButton = QtGui.QPushButton(self.frame)
        self.creatSubCtrlsButton.setEnabled(True)
        self.creatSubCtrlsButton.setGeometry(QtCore.QRect(110, 160, 91, 41))
        self.creatSubCtrlsButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/createSubCtrl.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.creatSubCtrlsButton.setIcon(icon3)
        self.creatSubCtrlsButton.setIconSize(QtCore.QSize(91, 41))
        self.creatSubCtrlsButton.setObjectName("creatSubCtrlsButton")
        self.jointRiggingButton = QtGui.QPushButton(self.frame)
        self.jointRiggingButton.setGeometry(QtCore.QRect(110, 10, 91, 41))
        self.jointRiggingButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/jointRig.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.jointRiggingButton.setIcon(icon4)
        self.jointRiggingButton.setIconSize(QtCore.QSize(91, 41))
        self.jointRiggingButton.setObjectName("jointRiggingButton")
        self.backToHairButton_5 = QtGui.QPushButton(self.frame)
        self.backToHairButton_5.setEnabled(False)
        self.backToHairButton_5.setGeometry(QtCore.QRect(210, 210, 91, 41))
        self.backToHairButton_5.setText("")
        self.backToHairButton_5.setObjectName("backToHairButton_5")
        self.sliderJointOptimizeButton = QtGui.QPushButton(self.frame)
        self.sliderJointOptimizeButton.setEnabled(True)
        self.sliderJointOptimizeButton.setGeometry(QtCore.QRect(10, 10, 91, 41))
        self.sliderJointOptimizeButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/sliderJointOptimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sliderJointOptimizeButton.setIcon(icon5)
        self.sliderJointOptimizeButton.setIconSize(QtCore.QSize(91, 41))
        self.sliderJointOptimizeButton.setObjectName("sliderJointOptimizeButton")
        self.branchesCtrlButton = QtGui.QPushButton(self.frame)
        self.branchesCtrlButton.setEnabled(True)
        self.branchesCtrlButton.setGeometry(QtCore.QRect(10, 160, 91, 41))
        self.branchesCtrlButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/branchesCtrl.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.branchesCtrlButton.setIcon(icon6)
        self.branchesCtrlButton.setIconSize(QtCore.QSize(91, 41))
        self.branchesCtrlButton.setObjectName("branchesCtrlButton")
        self.backToHairButton = QtGui.QPushButton(self.frame)
        self.backToHairButton.setGeometry(QtCore.QRect(110, 60, 91, 41))
        self.backToHairButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/backToHair.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backToHairButton.setIcon(icon7)
        self.backToHairButton.setIconSize(QtCore.QSize(91, 41))
        self.backToHairButton.setObjectName("backToHairButton")
        self.addBlendAttrButton = QtGui.QPushButton(self.frame)
        self.addBlendAttrButton.setEnabled(True)
        self.addBlendAttrButton.setGeometry(QtCore.QRect(10, 110, 91, 41))
        self.addBlendAttrButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/blendAttr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addBlendAttrButton.setIcon(icon8)
        self.addBlendAttrButton.setIconSize(QtCore.QSize(91, 41))
        self.addBlendAttrButton.setObjectName("addBlendAttrButton")
        self.hairButton_6 = QtGui.QPushButton(self.frame)
        self.hairButton_6.setEnabled(False)
        self.hairButton_6.setGeometry(QtCore.QRect(110, 260, 91, 41))
        self.hairButton_6.setText("")
        self.hairButton_6.setObjectName("hairButton_6")
        self.hairButton_5 = QtGui.QPushButton(self.frame)
        self.hairButton_5.setEnabled(False)
        self.hairButton_5.setGeometry(QtCore.QRect(110, 210, 91, 41))
        self.hairButton_5.setText("")
        self.hairButton_5.setObjectName("hairButton_5")
        self.BSSplitButton = QtGui.QPushButton(self.frame)
        self.BSSplitButton.setEnabled(True)
        self.BSSplitButton.setGeometry(QtCore.QRect(210, 60, 91, 41))
        self.BSSplitButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/BSSplit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BSSplitButton.setIcon(icon9)
        self.BSSplitButton.setIconSize(QtCore.QSize(91, 41))
        self.BSSplitButton.setObjectName("BSSplitButton")
        self.growButton_6 = QtGui.QPushButton(self.frame)
        self.growButton_6.setEnabled(False)
        self.growButton_6.setGeometry(QtCore.QRect(10, 260, 91, 41))
        self.growButton_6.setText("")
        self.growButton_6.setObjectName("growButton_6")
        self.growButton_5 = QtGui.QPushButton(self.frame)
        self.growButton_5.setEnabled(False)
        self.growButton_5.setGeometry(QtCore.QRect(10, 210, 91, 41))
        self.growButton_5.setText("")
        self.growButton_5.setObjectName("growButton_5")
        self.growButton = QtGui.QPushButton(self.frame)
        self.growButton.setGeometry(QtCore.QRect(210, 10, 91, 41))
        self.growButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/growAnim.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.growButton.setIcon(icon10)
        self.growButton.setIconSize(QtCore.QSize(91, 41))
        self.growButton.setObjectName("growButton")
        moreRiggingToolsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(moreRiggingToolsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 331, 23))
        self.menubar.setObjectName("menubar")
        moreRiggingToolsWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(moreRiggingToolsWindow)
        self.statusbar.setObjectName("statusbar")
        moreRiggingToolsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(moreRiggingToolsWindow)
        QtCore.QMetaObject.connectSlotsByName(moreRiggingToolsWindow)

    def retranslateUi(self, moreRiggingToolsWindow):
        moreRiggingToolsWindow.setWindowTitle(QtGui.QApplication.translate("moreRiggingToolsWindow", "鍏朵粬璁剧疆宸ュ叿", None, QtGui.QApplication.UnicodeUTF8))

import otherToolIcons_rc
